import { PrismaClient, PricingTier } from '@prisma/client';

const prisma = new PrismaClient();

const categories = [
  {
    slug: 'ai-writing',
    name: 'AI Writing',
    description: 'AI-powered writing assistants and content generators',
    icon: '✍️',
    sortOrder: 1,
  },
  {
    slug: 'ai-image',
    name: 'AI Image',
    description: 'AI image generation and editing tools',
    icon: '🎨',
    sortOrder: 2,
  },
  {
    slug: 'ai-video',
    name: 'AI Video',
    description: 'AI video creation and editing platforms',
    icon: '🎬',
    sortOrder: 3,
  },
  {
    slug: 'ai-code',
    name: 'AI Coding',
    description: 'AI-powered coding assistants and IDEs',
    icon: '💻',
    sortOrder: 4,
  },
  {
    slug: 'ai-chat',
    name: 'AI Chat',
    description: 'AI chatbots and conversational AI',
    icon: '💬',
    sortOrder: 5,
  },
  {
    slug: 'ai-audio',
    name: 'AI Audio',
    description: 'AI voice and audio processing tools',
    icon: '🎵',
    sortOrder: 6,
  },
  {
    slug: 'ai-research',
    name: 'AI Research',
    description: 'AI tools for research and analysis',
    icon: '🔬',
    sortOrder: 7,
  },
  {
    slug: 'ai-productivity',
    name: 'AI Productivity',
    description: 'AI-powered productivity and automation tools',
    icon: '⚡',
    sortOrder: 8,
  },
];

const tools = [
  // AI Chat
  {
    slug: 'chatgpt',
    name: 'ChatGPT',
    tagline: 'AI-powered conversational assistant',
    description: 'ChatGPT is an AI-powered chatbot developed by OpenAI. It can answer questions, write code, create content, and assist with various tasks through natural language conversation. With GPT-4o, it offers enhanced capabilities including image understanding and faster responses.',
    website: 'https://chat.openai.com',
    categorySlug: 'ai-chat',
    pricingTier: PricingTier.FREEMIUM,
    priceStart: 20,
    hasFreeTier: true,
    hasTrial: false,
    features: ['Natural language conversations', 'Code generation', 'Content writing', 'Question answering', 'Multi-language support', 'Image understanding', 'Web browsing', 'Plugin ecosystem'],
    useCases: ['Customer support', 'Content creation', 'Programming help', 'Learning assistance', 'Brainstorming ideas', 'Document analysis'],
    githubStars: 0,
    productHuntVotes: 8500,
    trendingScore: 95,
    isFeatured: true,
    isActive: true,
  },
  {
    slug: 'claude',
    name: 'Claude',
    tagline: 'Anthropic\'s AI assistant with long context',
    description: 'Claude is an AI assistant created by Anthropic. It excels at thoughtful analysis, coding, writing, and complex reasoning tasks with a focus on helpfulness and safety. Claude 3.5 Sonnet offers state-of-the-art performance with a 200K context window.',
    website: 'https://claude.ai',
    categorySlug: 'ai-chat',
    pricingTier: PricingTier.FREEMIUM,
    priceStart: 20,
    hasFreeTier: true,
    hasTrial: false,
    features: ['Long context window (200K)', 'Document analysis', 'Code generation', 'Thoughtful reasoning', 'Safety-focused', 'Vision capabilities', 'Artifact generation'],
    useCases: ['Research assistance', 'Document analysis', 'Code review', 'Writing help', 'Data analysis', 'Long-form content'],
    githubStars: 0,
    productHuntVotes: 4200,
    trendingScore: 88,
    isFeatured: true,
    isActive: true,
  },
  {
    slug: 'gemini',
    name: 'Google Gemini',
    tagline: 'Google\'s most capable AI model',
    description: 'Gemini is Google\'s largest and most capable AI model, built to be multimodal from the ground up. It can understand and reason across text, images, audio, video, and code.',
    website: 'https://gemini.google.com',
    categorySlug: 'ai-chat',
    pricingTier: PricingTier.FREEMIUM,
    priceStart: 20,
    hasFreeTier: true,
    hasTrial: false,
    features: ['Multimodal understanding', 'Code generation', 'Image analysis', 'Real-time information', 'YouTube integration', 'Google Workspace integration'],
    useCases: ['Research', 'Content creation', 'Coding', 'Image analysis', 'Document processing'],
    githubStars: 0,
    productHuntVotes: 3100,
    trendingScore: 82,
    isFeatured: false,
    isActive: true,
  },
  {
    slug: 'perplexity',
    name: 'Perplexity AI',
    tagline: 'AI search engine with citations',
    description: 'Perplexity is an AI-powered search engine that provides direct answers with cited sources. It combines large language models with web search for accurate, up-to-date information.',
    website: 'https://perplexity.ai',
    categorySlug: 'ai-chat',
    pricingTier: PricingTier.FREEMIUM,
    priceStart: 20,
    hasFreeTier: true,
    hasTrial: false,
    features: ['Real-time web search', 'Cited sources', 'Follow-up questions', 'PDF analysis', 'Pro search modes', 'Mobile apps'],
    useCases: ['Research', 'Fact-checking', 'Learning', 'News analysis', 'Academic research'],
    githubStars: 0,
    productHuntVotes: 5600,
    trendingScore: 90,
    isFeatured: true,
    isActive: true,
  },
  {
    slug: 'poe',
    name: 'Poe',
    tagline: 'Platform for AI chatbots',
    description: 'Poe is a platform that lets you ask questions and have conversations with various AI chatbots, including GPT-4, Claude, and many custom bots.',
    website: 'https://poe.com',
    categorySlug: 'ai-chat',
    pricingTier: PricingTier.FREEMIUM,
    priceStart: 20,
    hasFreeTier: true,
    hasTrial: false,
    features: ['Multiple AI models', 'Custom bots', 'Mobile apps', 'Bot creation', 'Community bots'],
    useCases: ['AI comparison', 'Custom assistants', 'Learning', 'Entertainment'],
    githubStars: 0,
    productHuntVotes: 2800,
    trendingScore: 75,
    isFeatured: false,
    isActive: true,
  },
  // AI Image
  {
    slug: 'midjourney',
    name: 'Midjourney',
    tagline: 'AI image generation from text descriptions',
    description: 'Midjourney is an AI-powered image generation tool that creates stunning artwork from text descriptions. Known for its artistic style and high-quality outputs, it has become the go-to tool for digital artists and designers.',
    website: 'https://www.midjourney.com',
    categorySlug: 'ai-image',
    pricingTier: PricingTier.PAID,
    priceStart: 10,
    hasFreeTier: false,
    hasTrial: false,
    features: ['Text-to-image generation', 'High-resolution outputs', 'Artistic style rendering', 'Discord integration', 'Image variations', 'Style tuning', 'Character consistency'],
    useCases: ['Digital art creation', 'Marketing visuals', 'Concept art', 'Social media content', 'Book illustrations', 'Game assets'],
    githubStars: 0,
    productHuntVotes: 6200,
    trendingScore: 88,
    isFeatured: true,
    isActive: true,
  },
  {
    slug: 'stable-diffusion',
    name: 'Stable Diffusion',
    tagline: 'Open-source AI image generation',
    description: 'Stable Diffusion is an open-source AI model for generating images from text. It can run locally and has spawned a large ecosystem of tools and extensions, including ControlNet and LoRA.',
    website: 'https://stability.ai',
    categorySlug: 'ai-image',
    pricingTier: PricingTier.OPEN_SOURCE,
    hasFreeTier: true,
    hasTrial: false,
    features: ['Local execution', 'Text-to-image', 'Image-to-image', 'Inpainting', 'Custom model training', 'ControlNet', 'LoRA support'],
    useCases: ['Local AI art generation', 'Privacy-focused image creation', 'Custom model development', 'Research', 'Commercial projects', 'NSFW content (uncensored)'],
    githubStars: 65000,
    productHuntVotes: 3800,
    trendingScore: 85,
    isFeatured: true,
    isActive: true,
  },
  {
    slug: 'dalle',
    name: 'DALL-E 3',
    tagline: 'OpenAI\'s image generation model',
    description: 'DALL-E 3 is OpenAI\'s latest image generation model, offering improved prompt understanding and image quality. Integrated with ChatGPT for seamless text-to-image creation.',
    website: 'https://openai.com/dall-e-3',
    categorySlug: 'ai-image',
    pricingTier: PricingTier.FREEMIUM,
    priceStart: 20,
    hasFreeTier: true,
    hasTrial: false,
    features: ['Text-to-image', 'ChatGPT integration', 'High-quality outputs', 'Prompt rewriting', 'Safety filters', 'Commercial use rights'],
    useCases: ['Content creation', 'Marketing', 'Illustrations', 'Concept visualization'],
    githubStars: 0,
    productHuntVotes: 4200,
    trendingScore: 80,
    isFeatured: false,
    isActive: true,
  },
  {
    slug: 'leonardo',
    name: 'Leonardo.ai',
    tagline: 'AI art generator for game assets',
    description: 'Leonardo.ai is an AI art generator focused on creating game assets, concept art, and illustrations. Offers fine-tuned models for specific art styles.',
    website: 'https://leonardo.ai',
    categorySlug: 'ai-image',
    pricingTier: PricingTier.FREEMIUM,
    priceStart: 12,
    hasFreeTier: true,
    hasTrial: false,
    features: ['Game asset generation', 'Multiple fine-tuned models', 'Real-time canvas', '3D texture generation', 'Animation tools', 'API access'],
    useCases: ['Game development', 'Concept art', 'Character design', 'Environment art', 'Texture creation'],
    githubStars: 0,
    productHuntVotes: 2100,
    trendingScore: 78,
    isFeatured: false,
    isActive: true,
  },
  {
    slug: 'ideogram',
    name: 'Ideogram',
    tagline: 'AI image generation with text',
    description: 'Ideogram specializes in generating images with legible text, making it ideal for logos, posters, and marketing materials with typography.',
    website: 'https://ideogram.ai',
    categorySlug: 'ai-image',
    pricingTier: PricingTier.FREEMIUM,
    priceStart: 8,
    hasFreeTier: true,
    hasTrial: false,
    features: ['Text in images', 'Logo generation', 'Poster creation', 'Typography rendering', 'Style presets'],
    useCases: ['Logo design', 'Marketing materials', 'Social media graphics', 'Poster creation'],
    githubStars: 0,
    productHuntVotes: 1800,
    trendingScore: 72,
    isFeatured: false,
    isActive: true,
  },
  // AI Code
  {
    slug: 'github-copilot',
    name: 'GitHub Copilot',
    tagline: 'AI pair programmer for developers',
    description: 'GitHub Copilot is an AI-powered code completion tool that helps developers write code faster. It suggests whole lines or blocks of code as you type, trained on billions of lines of code.',
    website: 'https://github.com/features/copilot',
    categorySlug: 'ai-code',
    pricingTier: PricingTier.PAID,
    priceStart: 10,
    hasFreeTier: false,
    hasTrial: true,
    features: ['Code completion', 'Function generation', 'Test generation', 'Multiple language support', 'IDE integration', 'Chat interface', 'Pull request summaries'],
    useCases: ['Software development', 'Learning new languages', 'Code review', 'Prototyping', 'Documentation', 'Legacy code understanding'],
    githubStars: 0,
    productHuntVotes: 7800,
    trendingScore: 92,
    isFeatured: true,
    isActive: true,
  },
  {
    slug: 'cursor',
    name: 'Cursor',
    tagline: 'AI-first code editor',
    description: 'Cursor is an AI-powered code editor built on VS Code. It offers intelligent code completion, natural language editing, and AI chat directly in your editor.',
    website: 'https://cursor.sh',
    categorySlug: 'ai-code',
    pricingTier: PricingTier.FREEMIUM,
    priceStart: 20,
    hasFreeTier: true,
    hasTrial: false,
    features: ['AI code completion', 'Natural language commands', 'Inline AI chat', 'Codebase understanding', 'VS Code compatible', 'Multi-file editing'],
    useCases: ['Full-stack development', 'Code refactoring', 'Learning codebases', 'Rapid prototyping'],
    githubStars: 0,
    productHuntVotes: 4500,
    trendingScore: 89,
    isFeatured: true,
    isActive: true,
  },
  {
    slug: 'tabnine',
    name: 'Tabnine',
    tagline: 'AI code completion for teams',
    description: 'Tabnine is an AI code completion tool that focuses on privacy and team collaboration. It can be self-hosted and trained on your private codebase.',
    website: 'https://www.tabnine.com',
    categorySlug: 'ai-code',
    pricingTier: PricingTier.FREEMIUM,
    priceStart: 12,
    hasFreeTier: true,
    hasTrial: false,
    features: ['Private AI models', 'Self-hosting option', 'Team collaboration', 'Code privacy', 'Multiple IDE support', 'Custom model training'],
    useCases: ['Enterprise development', 'Privacy-focused coding', 'Team onboarding', 'Code standardization'],
    githubStars: 0,
    productHuntVotes: 2200,
    trendingScore: 70,
    isFeatured: false,
    isActive: true,
  },
  {
    slug: 'replit-ghostwriter',
    name: 'Replit Ghostwriter',
    tagline: 'AI coding assistant in the cloud',
    description: 'Ghostwriter is Replit\'s AI coding assistant, integrated directly into their online IDE. It offers code generation, explanation, and debugging.',
    website: 'https://replit.com',
    categorySlug: 'ai-code',
    pricingTier: PricingTier.PAID,
    priceStart: 7,
    hasFreeTier: false,
    hasTrial: false,
    features: ['In-IDE AI assistant', 'Code generation', 'Error explanation', 'Code transformation', 'Cloud deployment'],
    useCases: ['Learning to code', 'Rapid prototyping', 'Teaching programming', 'Collaborative coding'],
    githubStars: 0,
    productHuntVotes: 1600,
    trendingScore: 68,
    isFeatured: false,
    isActive: true,
  },
  {
    slug: 'amazon-codewhisperer',
    name: 'Amazon CodeWhisperer',
    tagline: 'AWS AI code generator',
    description: 'Amazon CodeWhisperer is an AI-powered code generator from AWS. It provides code suggestions and security scanning for your code.',
    website: 'https://aws.amazon.com/codewhisperer',
    categorySlug: 'ai-code',
    pricingTier: PricingTier.FREEMIUM,
    priceStart: 19,
    hasFreeTier: true,
    hasTrial: false,
    features: ['Code suggestions', 'Security scanning', 'AWS integration', 'Reference tracking', 'IDE support'],
    useCases: ['AWS development', 'Security-conscious coding', 'Enterprise development'],
    githubStars: 0,
    productHuntVotes: 1200,
    trendingScore: 65,
    isFeatured: false,
    isActive: true,
  },
  // AI Writing
  {
    slug: 'jasper',
    name: 'Jasper',
    tagline: 'AI writing assistant for marketers',
    description: 'Jasper is an AI writing tool designed for marketing teams. It helps create blog posts, social media content, ad copy, and marketing materials at scale with brand voice consistency.',
    website: 'https://www.jasper.ai',
    categorySlug: 'ai-writing',
    pricingTier: PricingTier.PAID,
    priceStart: 49,
    hasFreeTier: false,
    hasTrial: true,
    features: ['Marketing templates', 'Brand voice customization', 'SEO optimization', 'Team collaboration', 'Content scheduling', 'Campaign management'],
    useCases: ['Blog writing', 'Social media content', 'Ad copy creation', 'Email marketing', 'Website copy', 'Marketing campaigns'],
    githubStars: 0,
    productHuntVotes: 2900,
    trendingScore: 75,
    isFeatured: true,
    isActive: true,
  },
  {
    slug: 'copy-ai',
    name: 'Copy.ai',
    tagline: 'AI copywriting tool',
    description: 'Copy.ai helps you write marketing copy, blog posts, social media content, and more. It offers workflows for specific use cases and team collaboration features.',
    website: 'https://www.copy.ai',
    categorySlug: 'ai-writing',
    pricingTier: PricingTier.FREEMIUM,
    priceStart: 36,
    hasFreeTier: true,
    hasTrial: false,
    features: ['90+ copywriting tools', 'Blog post wizard', 'Social media templates', 'Email sequences', 'Workflows', 'Team workspaces'],
    useCases: ['Marketing copy', 'Blog posts', 'Social media', 'Email marketing', 'Product descriptions'],
    githubStars: 0,
    productHuntVotes: 2400,
    trendingScore: 72,
    isFeatured: false,
    isActive: true,
  },
  {
    slug: 'notion-ai',
    name: 'Notion AI',
    tagline: 'AI writing assistant in Notion',
    description: 'Notion AI integrates AI writing capabilities directly into your Notion workspace. It can draft content, summarize notes, and help with brainstorming.',
    website: 'https://notion.so/product/ai',
    categorySlug: 'ai-writing',
    pricingTier: PricingTier.PAID,
    priceStart: 10,
    hasFreeTier: false,
    hasTrial: false,
    features: ['In-app AI writing', 'Note summarization', 'Content drafting', 'Brainstorming', 'Translation', 'Q&A on notes'],
    useCases: ['Note-taking', 'Documentation', 'Project planning', 'Meeting notes', 'Knowledge management'],
    githubStars: 0,
    productHuntVotes: 3200,
    trendingScore: 78,
    isFeatured: false,
    isActive: true,
  },
  {
    slug: 'grammarly',
    name: 'Grammarly',
    tagline: 'AI writing assistant',
    description: 'Grammarly helps you write mistake-free in any app. It checks spelling, grammar, punctuation, and offers style suggestions powered by AI.',
    website: 'https://grammarly.com',
    categorySlug: 'ai-writing',
    pricingTier: PricingTier.FREEMIUM,
    priceStart: 12,
    hasFreeTier: true,
    hasTrial: false,
    features: ['Grammar checking', 'Style suggestions', 'Tone detection', 'Plagiarism detection', 'Browser extension', 'Mobile keyboard'],
    useCases: ['Email writing', 'Academic writing', 'Professional communication', 'Content editing'],
    githubStars: 0,
    productHuntVotes: 5100,
    trendingScore: 82,
    isFeatured: true,
    isActive: true,
  },
  {
    slug: 'writesonic',
    name: 'Writesonic',
    tagline: 'AI writer and paraphrasing tool',
    description: 'Writesonic is an AI writing tool that helps create SEO-optimized content, paraphrase text, and generate marketing copy.',
    website: 'https://writesonic.com',
    categorySlug: 'ai-writing',
    pricingTier: PricingTier.FREEMIUM,
    priceStart: 16,
    hasFreeTier: true,
    hasTrial: false,
    features: ['AI article writer', 'Paraphrasing tool', 'SEO optimization', 'Chatsonic chatbot', 'Botsonic custom bots', 'Landing page generator'],
    useCases: ['Blog writing', 'Content marketing', 'Paraphrasing', 'Chatbot creation'],
    githubStars: 0,
    productHuntVotes: 1900,
    trendingScore: 68,
    isFeatured: false,
    isActive: true,
  },
  // AI Video
  {
    slug: 'runway',
    name: 'Runway ML',
    tagline: 'AI video editing and generation',
    description: 'Runway ML is a creative suite with AI-powered video editing tools. Features include text-to-video, video inpainting, motion tracking, and green screen removal.',
    website: 'https://runwayml.com',
    categorySlug: 'ai-video',
    pricingTier: PricingTier.FREEMIUM,
    priceStart: 15,
    hasFreeTier: true,
    hasTrial: false,
    features: ['Text-to-video', 'Video inpainting', 'Green screen', 'Motion tracking', 'Style transfer', 'Frame interpolation', 'Generative audio'],
    useCases: ['Video production', 'Content creation', 'Film editing', 'Social media videos', 'Visual effects', 'Music videos'],
    githubStars: 0,
    productHuntVotes: 5100,
    trendingScore: 87,
    isFeatured: true,
    isActive: true,
  },
  {
    slug: 'pika',
    name: 'Pika Labs',
    tagline: 'AI video generation platform',
    description: 'Pika is an AI video generation platform that creates videos from text and images. Known for its cinematic quality and ease of use.',
    website: 'https://pika.art',
    categorySlug: 'ai-video',
    pricingTier: PricingTier.FREEMIUM,
    priceStart: 10,
    hasFreeTier: true,
    hasTrial: false,
    features: ['Text-to-video', 'Image-to-video', 'Video extension', 'Cinematic styles', 'Camera controls', 'Lip sync'],
    useCases: ['Short films', 'Social media content', 'Marketing videos', 'Creative projects'],
    githubStars: 0,
    productHuntVotes: 2800,
    trendingScore: 84,
    isFeatured: false,
    isActive: true,
  },
  {
    slug: 'synthesia',
    name: 'Synthesia',
    tagline: 'AI video creation with avatars',
    description: 'Synthesia creates professional videos with AI avatars. Simply type your script and choose an avatar to generate videos in minutes.',
    website: 'https://www.synthesia.io',
    categorySlug: 'ai-video',
    pricingTier: PricingTier.PAID,
    priceStart: 22,
    hasFreeTier: false,
    hasTrial: false,
    features: ['AI avatars', 'Text-to-speech', 'Multiple languages', 'Custom avatars', 'Screen recording', 'Video templates'],
    useCases: ['Training videos', 'Marketing content', 'Internal communications', 'Product demos', 'E-learning'],
    githubStars: 0,
    productHuntVotes: 3400,
    trendingScore: 79,
    isFeatured: false,
    isActive: true,
  },
  {
    slug: 'heygen',
    name: 'HeyGen',
    tagline: 'AI video platform for business',
    description: 'HeyGen is an AI video generation platform for creating marketing, training, and personalized videos with AI avatars and voices.',
    website: 'https://www.heygen.com',
    categorySlug: 'ai-video',
    pricingTier: PricingTier.PAID,
    priceStart: 29,
    hasFreeTier: false,
    hasTrial: true,
    features: ['AI avatars', 'Voice cloning', 'Video translation', 'API access', 'Custom templates', 'Streaming avatar'],
    useCases: ['Marketing videos', 'Sales outreach', 'Training content', 'Personalized video', 'Live streaming'],
    githubStars: 0,
    productHuntVotes: 2100,
    trendingScore: 76,
    isFeatured: false,
    isActive: true,
  },
  {
    slug: 'descript',
    name: 'Descript',
    tagline: 'AI-powered video and audio editor',
    description: 'Descript is a collaborative audio/video editor that works like a doc. It includes transcription, overdub, and AI editing features.',
    website: 'https://www.descript.com',
    categorySlug: 'ai-video',
    pricingTier: PricingTier.FREEMIUM,
    priceStart: 15,
    hasFreeTier: true,
    hasTrial: false,
    features: ['Text-based editing', 'Overdub voice cloning', 'Transcription', 'Screen recording', 'Multitrack editing', 'AI actions'],
    useCases: ['Podcast editing', 'Video editing', 'Transcription', 'Content creation', 'Screen recording'],
    githubStars: 0,
    productHuntVotes: 4300,
    trendingScore: 81,
    isFeatured: false,
    isActive: true,
  },
  // AI Audio
  {
    slug: 'elevenlabs',
    name: 'ElevenLabs',
    tagline: 'AI voice generation platform',
    description: 'ElevenLabs provides high-quality AI voice generation with realistic speech synthesis. Create voiceovers, clone voices, and generate audio content in multiple languages.',
    website: 'https://elevenlabs.io',
    categorySlug: 'ai-audio',
    pricingTier: PricingTier.FREEMIUM,
    priceStart: 5,
    hasFreeTier: true,
    hasTrial: false,
    features: ['Voice cloning', 'Multi-language support', 'High-quality synthesis', 'Voice library', 'API access', 'Projects for long-form', 'Sound effects'],
    useCases: ['Voiceovers', 'Audiobooks', 'Podcast production', 'Video narration', 'Accessibility', 'Game development'],
    githubStars: 0,
    productHuntVotes: 3400,
    trendingScore: 86,
    isFeatured: true,
    isActive: true,
  },
  {
    slug: 'murf',
    name: 'Murf AI',
    tagline: 'AI voice generator for professionals',
    description: 'Murf AI offers studio-quality AI voiceovers for videos, presentations, and e-learning. Features 120+ voices in 20+ languages.',
    website: 'https://murf.ai',
    categorySlug: 'ai-audio',
    pricingTier: PricingTier.FREEMIUM,
    priceStart: 29,
    hasFreeTier: true,
    hasTrial: false,
    features: ['120+ AI voices', 'Voice changer', 'Google Slides add-on', 'Canva integration', 'Team collaboration', 'Voice cloning'],
    useCases: ['E-learning', 'Presentations', 'YouTube videos', 'Podcasts', 'IVR systems'],
    githubStars: 0,
    productHuntVotes: 1800,
    trendingScore: 71,
    isFeatured: false,
    isActive: true,
  },
  {
    slug: 'speechify',
    name: 'Speechify',
    tagline: 'Text-to-speech app',
    description: 'Speechify turns text into natural-sounding speech. Listen to documents, articles, PDFs, and books with high-quality AI voices.',
    website: 'https://speechify.com',
    categorySlug: 'ai-audio',
    pricingTier: PricingTier.FREEMIUM,
    priceStart: 11,
    hasFreeTier: true,
    hasTrial: false,
    features: ['Text-to-speech', 'PDF reading', 'Browser extension', 'Mobile apps', 'Celebrity voices', 'Speed control'],
    useCases: ['Reading assistance', 'Learning', 'Productivity', 'Accessibility', 'Language learning'],
    githubStars: 0,
    productHuntVotes: 2600,
    trendingScore: 74,
    isFeatured: false,
    isActive: true,
  },
  {
    slug: 'udio',
    name: 'Udio',
    tagline: 'AI music generation',
    description: 'Udio is an AI music generation platform that creates original songs from text descriptions. It can generate vocals, instruments, and full compositions.',
    website: 'https://udio.com',
    categorySlug: 'ai-audio',
    pricingTier: PricingTier.FREEMIUM,
    priceStart: 10,
    hasFreeTier: true,
    hasTrial: false,
    features: ['Text-to-music', 'Vocal generation', 'Style mixing', 'Remix capability', 'High-quality audio'],
    useCases: ['Music creation', 'Soundtrack production', 'Jingles', 'Creative projects'],
    githubStars: 0,
    productHuntVotes: 2200,
    trendingScore: 83,
    isFeatured: false,
    isActive: true,
  },
  {
    slug: 'suno',
    name: 'Suno',
    tagline: 'AI music creation platform',
    description: 'Suno creates original music from text prompts. Generate songs with vocals, instruments, and professional-quality production.',
    website: 'https://suno.com',
    categorySlug: 'ai-audio',
    pricingTier: PricingTier.FREEMIUM,
    priceStart: 10,
    hasFreeTier: true,
    hasTrial: false,
    features: ['Text-to-song', 'Vocal synthesis', 'Multiple genres', 'Custom lyrics', 'High-quality export'],
    useCases: ['Music production', 'Content creation', 'Game audio', 'Personal projects'],
    githubStars: 0,
    productHuntVotes: 3100,
    trendingScore: 85,
    isFeatured: true,
    isActive: true,
  },
  // AI Research
  {
    slug: 'elicit',
    name: 'Elicit',
    tagline: 'AI research assistant',
    description: 'Elicit uses AI to help researchers find relevant papers, extract key information, and synthesize findings. It automates literature review workflows.',
    website: 'https://elicit.org',
    categorySlug: 'ai-research',
    pricingTier: PricingTier.FREEMIUM,
    priceStart: 10,
    hasFreeTier: true,
    hasTrial: false,
    features: ['Paper search', 'Data extraction', 'Synthesis', 'Citation analysis', 'Research workflows'],
    useCases: ['Literature review', 'Academic research', 'Systematic reviews', 'Evidence synthesis'],
    githubStars: 0,
    productHuntVotes: 1500,
    trendingScore: 73,
    isFeatured: false,
    isActive: true,
  },
  {
    slug: 'consensus',
    name: 'Consensus',
    tagline: 'AI-powered scientific search',
    description: 'Consensus searches through peer-reviewed research to find answers to your questions with cited sources.',
    website: 'https://consensus.app',
    categorySlug: 'ai-research',
    pricingTier: PricingTier.FREEMIUM,
    priceStart: 8,
    hasFreeTier: true,
    hasTrial: false,
    features: ['Scientific search', 'Consensus mapping', 'Citation tracking', 'Research snapshots', 'Browser extension'],
    useCases: ['Academic research', 'Evidence-based decisions', 'Literature review', 'Fact-checking'],
    githubStars: 0,
    productHuntVotes: 1700,
    trendingScore: 71,
    isFeatured: false,
    isActive: true,
  },
  {
    slug: 'scite',
    name: 'scite',
    tagline: 'Smart citations for research',
    description: 'scite helps researchers discover and evaluate scientific articles through Smart Citations that show how papers have been cited.',
    website: 'https://scite.ai',
    categorySlug: 'ai-research',
    pricingTier: PricingTier.FREEMIUM,
    priceStart: 15,
    hasFreeTier: true,
    hasTrial: false,
    features: ['Smart Citations', 'Citation context', 'Reference check', 'Browser extension', 'Zotero integration'],
    useCases: ['Citation analysis', 'Research evaluation', 'Literature review', 'Academic writing'],
    githubStars: 0,
    productHuntVotes: 1200,
    trendingScore: 66,
    isFeatured: false,
    isActive: true,
  },
  // AI Productivity
  {
    slug: 'otter',
    name: 'Otter.ai',
    tagline: 'AI meeting assistant',
    description: 'Otter.ai transcribes meetings in real-time, generates summaries, and extracts action items. It integrates with Zoom, Google Meet, and Microsoft Teams.',
    website: 'https://otter.ai',
    categorySlug: 'ai-productivity',
    pricingTier: PricingTier.FREEMIUM,
    priceStart: 10,
    hasFreeTier: true,
    hasTrial: false,
    features: ['Real-time transcription', 'Meeting summaries', 'Action items', 'Slide capture', 'Collaboration features', 'Calendar integration'],
    useCases: ['Meeting notes', 'Interviews', 'Lectures', 'Team collaboration'],
    githubStars: 0,
    productHuntVotes: 2900,
    trendingScore: 77,
    isFeatured: false,
    isActive: true,
  },
  {
    slug: 'mem',
    name: 'Mem',
    tagline: 'AI-powered notes and workspace',
    description: 'Mem is an AI-powered workspace that organizes your notes, documents, and knowledge. It uses AI to surface relevant information when you need it.',
    website: 'https://mem.ai',
    categorySlug: 'ai-productivity',
    pricingTier: PricingTier.FREEMIUM,
    priceStart: 10,
    hasFreeTier: true,
    hasTrial: false,
    features: ['AI search', 'Smart collections', 'Chat with notes', 'Knowledge graph', 'Team collaboration'],
    useCases: ['Note-taking', 'Knowledge management', 'Project management', 'Team wiki'],
    githubStars: 0,
    productHuntVotes: 2000,
    trendingScore: 69,
    isFeatured: false,
    isActive: true,
  },
  {
    slug: 'tldv',
    name: 'tl;dv',
    tagline: 'AI meeting recorder',
    description: 'tl;dv records and transcribes meetings, then uses AI to generate summaries, highlight key moments, and create searchable archives.',
    website: 'https://tldv.io',
    categorySlug: 'ai-productivity',
    pricingTier: PricingTier.FREEMIUM,
    priceStart: 18,
    hasFreeTier: true,
    hasTrial: false,
    features: ['Meeting recording', 'AI summaries', 'Timestamp highlights', 'Multi-language', 'CRM integration', 'Clip sharing'],
    useCases: ['Sales calls', 'User research', 'Team meetings', 'Training sessions'],
    githubStars: 0,
    productHuntVotes: 1600,
    trendingScore: 67,
    isFeatured: false,
    isActive: true,
  },
  {
    slug: 'fireflies',
    name: 'Fireflies.ai',
    tagline: 'AI conversation intelligence',
    description: 'Fireflies.ai records, transcribes, and analyzes meetings. It provides conversation intelligence for sales and recruiting teams.',
    website: 'https://fireflies.ai',
    categorySlug: 'ai-productivity',
    pricingTier: PricingTier.FREEMIUM,
    priceStart: 10,
    hasFreeTier: true,
    hasTrial: false,
    features: ['Meeting transcription', 'Conversation analytics', 'CRM integration', 'Topic tracking', 'Video recording'],
    useCases: ['Sales coaching', 'Recruiting', 'Team meetings', 'Training analysis'],
    githubStars: 0,
    productHuntVotes: 2300,
    trendingScore: 70,
    isFeatured: false,
    isActive: true,
  },
];

const tags = [
  'Chatbot', 'Image Generation', 'Code Assistant', 'Writing', 'Video', 'Audio', 'Research', 'Productivity',
  'Free', 'Open Source', 'API', 'Mobile App', 'Browser Extension', 'Enterprise', 'Creative', 'Marketing',
  'SEO', 'Translation', 'Summarization', 'Data Analysis', 'Automation', 'Collaboration', 'Education',
  'Design', '3D', 'Voice', 'Music', 'Transcription', 'Meeting', 'Documentation', 'Social Media',
];

async function main() {
  console.log('🌱 Starting database seed...\n');

  // Clear existing data
  console.log('Clearing existing data...');
  await prisma.priceHistory.deleteMany();
  await prisma.tool.deleteMany();
  await prisma.category.deleteMany();
  await prisma.tag.deleteMany();
  console.log('✅ Data cleared\n');

  // Create categories
  console.log('Creating categories...');
  const categoryMap = new Map();
  for (const category of categories) {
    const created = await prisma.category.create({
      data: {
        slug: category.slug,
        name: category.name,
        description: category.description,
        icon: category.icon,
        sortOrder: category.sortOrder,
      },
    });
    categoryMap.set(category.slug, created.id);
    console.log(`  ✅ ${category.name}`);
  }
  console.log('');

  // Create tags
  console.log('Creating tags...');
  const tagMap = new Map();
  for (const tagName of tags) {
    const created = await prisma.tag.create({
      data: { name: tagName },
    });
    tagMap.set(tagName, created.id);
  }
  console.log(`  ✅ ${tags.length} tags created\n`);

  // Create tools
  console.log('Creating tools...');
  for (const tool of tools) {
    const categoryId = categoryMap.get(tool.categorySlug);
    if (!categoryId) {
      console.log(`  ⚠️ Skipping ${tool.name} - category not found`);
      continue;
    }

    // Assign random tags (3-5 tags per tool)
    const toolTagNames = tags
      .sort(() => Math.random() - 0.5)
      .slice(0, Math.floor(Math.random() * 3) + 3);

    const toolTagIds = toolTagNames
      .map(name => tagMap.get(name))
      .filter((id): id is string => !!id);

    await prisma.tool.create({
      data: {
        slug: tool.slug,
        name: tool.name,
        tagline: tool.tagline,
        description: tool.description,
        website: tool.website,
        categoryId: categoryId,
        pricingTier: tool.pricingTier,
        priceStart: tool.priceStart,
        hasFreeTier: tool.hasFreeTier,
        hasTrial: tool.hasTrial,
        features: tool.features,
        useCases: tool.useCases,
        githubStars: tool.githubStars,
        productHuntVotes: tool.productHuntVotes,
        trendingScore: tool.trendingScore,
        isFeatured: tool.isFeatured,
        isActive: tool.isActive,
        Tag: {
          connect: toolTagIds.map(id => ({ id })),
        },
      },
    });
    console.log(`  ✅ ${tool.name}`);
  }
  console.log('');

  // Create price history for some tools
  console.log('Creating price history...');
  const allTools = await prisma.tool.findMany();
  for (const tool of allTools.slice(0, 10)) {
    if (tool.priceStart) {
      await prisma.priceHistory.create({
        data: {
          toolId: tool.id,
          price: tool.priceStart * (0.8 + Math.random() * 0.4),
          pricingTier: tool.pricingTier,
        },
      });
    }
  }
  console.log('✅ Price history created\n');

  // Summary
  const stats = await Promise.all([
    prisma.category.count(),
    prisma.tool.count(),
    prisma.tag.count(),
  ]);

  console.log('📊 Seed completed!');
  console.log(`   Categories: ${stats[0]}`);
  console.log(`   Tools: ${stats[1]}`);
  console.log(`   Tags: ${stats[2]}`);
}

main()
  .catch((e) => {
    console.error('❌ Seed failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
