/**
 * Use multiple Logo APIs to get real logos
 * - Clearbit (already using)
 * - CompanyEnrich (https://api.companyenrich.com/logo/)
 * - DeBounce (https://logo.debounce.io/)
 */

import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// Extended tool domain mappings
const toolDomains: Record<string, string> = {
  // Already done via Clearbit
  
  // Additional tools for CompanyEnrich/DeBounce
  'ChatGPT': 'openai.com',
  'Claude': 'anthropic.com',
  'Stable Diffusion': 'stability.ai',
  'DALL-E': 'openai.com',
  'Cursor': 'cursor.sh',
  'Amazon CodeWhisperer': 'aws.amazon.com',
  'Speechify': 'speechify.com',
  'Udio': 'udio.com',
  'Suno': 'suno.ai',
  'Elicit': 'elicit.org',
  'Consensus': 'consensus.app',
  'Hugging Face': 'huggingface.co',
  'Replicate': 'replicate.com',
  'Poe': 'poe.com',
  'Character.AI': 'character.ai',
  'You.com': 'you.com',
  'Perplexity': 'perplexity.ai',
  'Phind': 'phind.com',
  'Vercel': 'vercel.com',
  'Netlify': 'netlify.com',
  'Supabase': 'supabase.com',
  'Firebase': 'firebase.google.com',
  'MongoDB': 'mongodb.com',
  'Redis': 'redis.io',
  'PostgreSQL': 'postgresql.org',
  'Docker': 'docker.com',
  'Kubernetes': 'kubernetes.io',
  'GitHub': 'github.com',
  'GitLab': 'gitlab.com',
  'Bitbucket': 'bitbucket.org',
  'Slack': 'slack.com',
  'Discord': 'discord.com',
  'Zoom': 'zoom.us',
  'Notion': 'notion.so',
  'Linear': 'linear.app',
  'Figma': 'figma.com',
  'Sketch': 'sketch.com',
  'Adobe XD': 'adobe.com',
  'Canva': 'canva.com',
  'Grammarly': 'grammarly.com',
  'Jasper': 'jasper.ai',
  'Copy.ai': 'copy.ai',
  'Writesonic': 'writesonic.com',
  'Rytr': 'rytr.me',
  'Synthesia': 'synthesia.io',
  'HeyGen': 'heygen.com',
  'Runway': 'runwayml.com',
  'Pika': 'pika.art',
  'Midjourney': 'midjourney.com',
  'Leonardo.ai': 'leonardo.ai',
  'Ideogram': 'ideogram.ai',
  'Playground AI': 'playgroundai.com',
  'NightCafe': 'nightcafe.studio',
  'Artbreeder': 'artbreeder.com',
  'DeepAI': 'deepai.org',
  'Remove.bg': 'remove.bg',
  'LetsEnhance': 'letsenhance.io',
  'BigJPG': 'bigjpg.com',
  'Upscayl': 'upscayl.org',
  'ImgUpscaler': 'imgupscaler.com',
  'PhotoRoom': 'photoroom.com',
  'Clipdrop': 'clipdrop.co',
  'Stability AI': 'stability.ai',
  'Civitai': 'civitai.com',
  'Tensor.Art': 'tensor.art',
  'SeaArt': 'seaart.ai',
  'LiblibAI': 'liblib.art',
  'WHEE': 'whee.com',
  'Vega AI': 'vegaai.net',
  '6pen Art': '6pen.art',
  'Jimeng': 'jimeng.jianying.com',
  'Dreamina': 'dreamina.capcut.com',
  'ZMO.AI': 'zmo.ai',
  'Anime Art Studio': 'animeart.studio',
  'Waifu Labs': 'waifulabs.com',
  'This Person Does Not Exist': 'thispersondoesnotexist.com',
  'Generated Photos': 'generated.photos',
  'FaceSwapper': 'faceswapper.ai',
  'Reface': 'reface.ai',
  'Avatarify': 'avatarify.ai',
  'Lensa': 'lensa.app',
  'Remini': 'remini.ai',
  'FaceApp': 'faceapp.com',
  'Meitu': 'meitu.com',
  'BeautyPlus': 'beautyplus.com',
  'YouCam Makeup': 'perfectcorp.com',
  'Facetune': 'facetuneapp.com',
  'Picsart': 'picsart.com',
  'VSCO': 'vsco.co',
  'Snapseed': 'google.com',
  'Lightroom': 'adobe.com',
  'Photoshop': 'adobe.com',
  'GIMP': 'gimp.org',
  'Canva AI': 'canva.com',
  'Microsoft Designer': 'microsoft.com',
  'Adobe Express': 'adobe.com',
  'Krita': 'krita.org',
  'Inkscape': 'inkscape.org',
  'Blender': 'blender.org',
  'Cinema 4D': 'maxon.net',
  'Maya': 'autodesk.com',
  '3ds Max': 'autodesk.com',
  'ZBrush': 'maxon.net',
  'Substance Painter': 'adobe.com',
  'Houdini': 'sidefx.com',
  'Unreal Engine': 'unrealengine.com',
  'Unity': 'unity.com',
  'Godot': 'godotengine.org',
  'CryEngine': 'cryengine.com',
  'Lumberyard': 'aws.amazon.com',
  'GameMaker': 'gamemaker.io',
  'Construct': 'construct.net',
  'RPG Maker': 'rpgmakerweb.com',
  'RenPy': 'renpy.org',
  'Twine': 'twinery.org',
  'Ink': 'inklestudios.com',
  'ChoiceScript': 'choiceofgames.com',
  'Bitsy': 'bitsy.bitsy.space',
  'PICO-8': 'lexaloffle.com',
  'TIC-80': 'tic80.com',
  'Scratch': 'scratch.mit.edu',
  'Blockly': 'developers.google.com',
  'MIT App Inventor': 'appinventor.mit.edu',
  'Thunkable': 'thunkable.com',
  'Adalo': 'adalo.com',
  'Bubble': 'bubble.io',
  'Webflow': 'webflow.com',
  'Framer': 'framer.com',
  'InVision': 'invisionapp.com',
  'Marvel': 'marvelapp.com',
  'Proto.io': 'proto.io',
  'Axure': 'axure.com',
  'Balsamiq': 'balsamiq.com',
  'Mockplus': 'mockplus.com',
  'Moqups': 'moqups.com',
  'Whimsical': 'whimsical.com',
  'Miro': 'miro.com',
  'Mural': 'mural.co',
  'Conceptboard': 'conceptboard.com',
  'Stormboard': 'stormboard.com',
  'Lucidchart': 'lucidchart.com',
  'Draw.io': 'diagrams.net',
  'Excalidraw': 'excalidraw.com',
  'Tldraw': 'tldraw.com',
  'FigJam': 'figma.com',
  'Miro AI': 'miro.com',
  'Mural AI': 'mural.co',
  'Notion AI': 'notion.so',
  'Coda AI': 'coda.io',
  'Airtable AI': 'airtable.com',
  'ClickUp AI': 'clickup.com',
  'Asana AI': 'asana.com',
  'Monday AI': 'monday.com',
  'Trello AI': 'trello.com',
  'Jira AI': 'atlassian.com',
  'Linear AI': 'linear.app',
  'Height': 'height.app',
  'Motion': 'usemotion.com',
  'Reclaim': 'reclaim.ai',
  'Clockwise': 'getclockwise.com',
  'Sunsama': 'sunsama.com',
  'Akiflow': 'akiflow.com',
  'Routine': 'routine.co',
  'Amie': 'amie.so',
  'Cron': 'cron.com',
  'Notion Calendar': 'notion.so',
  'Calendly': 'calendly.com',
  'When2meet': 'when2meet.com',
  'Doodle': 'doodle.com',
  'Cal.com': 'cal.com',
  'SavvyCal': 'savvycal.com',
  'Rallly': 'rallly.co',
  'Loom': 'loom.com',
  'Vidyard': 'vidyard.com',
  'Wistia': 'wistia.com',
  'Vimeo': 'vimeo.com',
  'YouTube': 'youtube.com',
  'Twitch': 'twitch.tv',
  'TikTok': 'tiktok.com',
  'Instagram': 'instagram.com',
  'Twitter': 'twitter.com',
  'LinkedIn': 'linkedin.com',
  'Facebook': 'facebook.com',
  'Reddit': 'reddit.com',
  'Telegram': 'telegram.org',
  'WhatsApp': 'whatsapp.com',
  'Signal': 'signal.org',
  'Teams': 'microsoft.com',
  'Google Meet': 'google.com',
  'Webex': 'webex.com',
  'GoToMeeting': 'gotomeeting.com',
  'BlueJeans': 'bluejeans.com',
  'Whereby': 'whereby.com',
  'Around': 'around.co',
  'Gather': 'gather.town',
  'Kumospace': 'kumospace.com',
  'Teamflow': 'teamflowhq.com',
  'Remo': 'remo.co',
  'Hopin': 'hopin.com',
  'Airmeet': 'airmeet.com',
  'Bizzabo': 'bizzabo.com',
  'Cvent': 'cvent.com',
  'Eventbrite': 'eventbrite.com',
  'Meetup': 'meetup.com',
  'Luma': 'lu.ma',
  'Partiful': 'partiful.com',
  'Dice': 'dice.fm',
  'Songkick': 'songkick.com',
  'Bandsintown': 'bandsintown.com',
  'Ticketmaster': 'ticketmaster.com',
  'StubHub': 'stubhub.com',
  'SeatGeek': 'seatgeek.com',
  'Vivid Seats': 'vividseats.com',
  'Gametime': 'gametime.co',
  'TickPick': 'tickpick.com',
  'Goldstar': 'goldstar.com',
  'TodayTix': 'todaytix.com',
  'BroadwayWorld': 'broadwayworld.com',
  'Playbill': 'playbill.com',
  'TheaterMania': 'theatermania.com',
  'StageAgent': 'stageagent.com',
  'Backstage': 'backstage.com',
  'Actors Access': 'actorsaccess.com',
  'Casting Networks': 'castingnetworks.com',
  'Casting Frontier': 'castingfrontier.com',
  'AACTA': 'aacta.org',
  'IMDb': 'imdb.com',
  'Rotten Tomatoes': 'rottentomatoes.com',
  'Metacritic': 'metacritic.com',
  'Letterboxd': 'letterboxd.com',
  'Trakt': 'trakt.tv',
  'TV Time': 'tvtime.com',
  'JustWatch': 'justwatch.com',
  'Reelgood': 'reelgood.com',
  'Stremio': 'stremio.com',
  'Plex': 'plex.tv',
  'Jellyfin': 'jellyfin.org',
  'Emby': 'emby.media',
  'Kodi': 'kodi.tv',
  'VLC': 'videolan.org',
  'MPV': 'mpv.io',
  'PotPlayer': 'potplayer.daum.net',
  'MPC-HC': 'mpc-hc.org',
  'Daum': 'daum.net',
  'Naver': 'naver.com',
  'Kakao': 'kakao.com',
  'Line': 'line.me',
  'WeChat': 'wechat.com',
  'QQ': 'qq.com',
  'Weibo': 'weibo.com',
  'Bilibili': 'bilibili.com',
  'Youku': 'youku.com',
  'iQiyi': 'iqiyi.com',
  'Tencent Video': 'v.qq.com',
  'Mango TV': 'mgtv.com',
  'Sohu Video': 'tv.sohu.com',
  'LeTV': 'le.com',
  'PPTV': 'pptv.com',
  'Dailymotion': 'dailymotion.com',
  'Veoh': 'veoh.com',
  'Metacafe': 'metacafe.com',
  'Break': 'break.com',
  'Funny or Die': 'funnyordie.com',
  'CollegeHumor': 'collegehumor.com',
  'Cracked': 'cracked.com',
  'The Onion': 'theonion.com',
  'ClickHole': 'clickhole.com',
  'Reductress': 'reductress.com',
  'McSweeney': 'mcsweeneys.net',
  'The New Yorker': 'newyorker.com',
  'The Atlantic': 'theatlantic.com',
  'Wired': 'wired.com',
  'TechCrunch': 'techcrunch.com',
  'The Verge': 'theverge.com',
  'Engadget': 'engadget.com',
  'Gizmodo': 'gizmodo.com',
  'Lifehacker': 'lifehacker.com',
  'Kotaku': 'kotaku.com',
  'Polygon': 'polygon.com',
  'IGN': 'ign.com',
  'GameSpot': 'gamespot.com',
  'Eurogamer': 'eurogamer.net',
  'PC Gamer': 'pcgamer.com',
  'Rock Paper Shotgun': 'rockpapershotgun.com',
  'Destructoid': 'destructoid.com',
  'VG247': 'vg247.com',
  'GamesRadar': 'gamesradar.com',
  'Game Informer': 'gameinformer.com',
  'Nintendo Life': 'nintendolife.com',
  'Push Square': 'pushsquare.com',
  'Pure Xbox': 'purexbox.com',
  'Android Central': 'androidcentral.com',
  'iMore': 'imore.com',
  'Windows Central': 'windowscentral.com',
  'MacRumors': 'macrumors.com',
  '9to5Mac': '9to5mac.com',
  '9to5Google': '9to5google.com',
  'Electrek': 'electrek.co',
  'Tesla': 'tesla.com',
  'SpaceX': 'spacex.com',
  'Neuralink': 'neuralink.com',
  'The Boring Company': 'boringcompany.com',
  'X': 'x.com',
  'Threads': 'threads.net',
  'Mastodon': 'mastodon.social',
  'Bluesky': 'bsky.app',
  'Post': 'post.news',
  'T2': 't2.social',
  'Pebble': 'pebble.is',
  'Hive Social': 'hivesocial.app',
  'Gas': 'gas.app',
  'NGL': 'ngl.link',
  'Sendit': 'sendit.app',
  'Locket': 'locket.camera',
  'BeReal': 'bereal.com',
  'Poparazzi': 'poparazzi.com',
  'Dispo': 'dispo.com',
  'Retro': 'retro.app',
  'Glass': 'glass.photo',
  'Unsplash': 'unsplash.com',
  'Pexels': 'pexels.com',
  'Pixabay': 'pixabay.com',
  'Freepik': 'freepik.com',
  'Shutterstock': 'shutterstock.com',
  'Getty Images': 'gettyimages.com',
  'iStock': 'istockphoto.com',
  'Adobe Stock': 'stock.adobe.com',
  'Dreamstime': 'dreamstime.com',
  '123RF': '123rf.com',
  'Depositphotos': 'depositphotos.com',
  'Bigstock': 'bigstockphoto.com',
  'Crello': 'crello.com',
  'Snappa': 'snappa.com',
  'Stencil': 'getstencil.com',
  'PicMonkey': 'picmonkey.com',
  'Fotor': 'fotor.com',
  'BeFunky': 'befunky.com',
  'Pixlr': 'pixlr.com',
  'Photopea': 'photopea.com',
  'Sumopaint': 'sumopaint.com',
  'Kleki': 'kleki.com',
  'Sketchpad': 'sketch.io',
  'AutoDraw': 'autodraw.com',
  'Quick, Draw': 'quickdraw.withgoogle.com',
  'This X Does Not Exist': 'thisxdoesnotexist.com',
  'Which Face Is Real': 'whichfaceisreal.com',
  'FakeCatcher': 'fakecatcher.intel.com',
  'Reality Defender': 'realitydefender.com',
  'Truepic': 'truepic.com',
  'Content Authenticity Initiative': 'contentauthenticity.org',
  'Project Origin': 'projectorigin.org',
  'Coalition for Content Provenance and Authenticity': 'c2pa.org',
  'Starling Lab': 'starlinglab.org',
  'Proofmode': 'proofmode.org',
  'Numbers Protocol': 'numbersprotocol.io',
  'Capture': 'captureapp.xyz',
  'Blockchain': 'blockchain.com',
  'Coinbase': 'coinbase.com',
  'Binance': 'binance.com',
  'Kraken': 'kraken.com',
  'Gemini': 'gemini.com',
  'Crypto.com': 'crypto.com',
  'FTX': 'ftx.com',
  'KuCoin': 'kucoin.com',
  'Huobi': 'huobi.com',
  'OKX': 'okx.com',
  'Bybit': 'bybit.com',
  'Bitfinex': 'bitfinex.com',
  'Bitstamp': 'bitstamp.net',
  'Bittrex': 'bittrex.com',
  'Poloniex': 'poloniex.com',
  'Gate.io': 'gate.io',
  'MEXC': 'mexc.com',
  'LBank': 'lbank.info',
  'Bitget': 'bitget.com',
  'Phemex': 'phemex.com',
  'Deribit': 'deribit.com',
  'dYdX': 'dydx.exchange',
  'GMX': 'gmx.io',
  'Perpetual Protocol': 'perp.com',
  'Synthetix': 'synthetix.io',
  'Aave': 'aave.com',
  'Compound': 'compound.finance',
  'MakerDAO': 'makerdao.com',
  'Uniswap': 'uniswap.org',
  'SushiSwap': 'sushi.com',
  'PancakeSwap': 'pancakeswap.finance',
  'Curve': 'curve.fi',
  'Balancer': 'balancer.fi',
  '1inch': '1inch.io',
  '0x': '0x.org',
  'Matcha': 'matcha.xyz',
  'Paraswap': 'paraswap.io',
  'CowSwap': 'cow.fi',
  'OpenSea': 'opensea.io',
  'Blur': 'blur.io',
  'Magic Eden': 'magiceden.io',
  'Tensor': 'tensor.trade',
  'LooksRare': 'looksrare.org',
  'X2Y2': 'x2y2.io',
  'Sudoswap': 'sudoswap.xyz',
  'NFTfi': 'nftfi.com',
  'Arcade': 'arcade.xyz',
  'BendDAO': 'benddao.xyz',
  'JPEGd': 'jpegd.io',
  'Pine': 'pine.loans',
  'Gondi': 'gondi.xyz',
  'Astaria': 'astaria.xyz',
  'MetaStreet': 'metastreet.xyz',
  'Backed': 'backed.xyz',
  'Centrifuge': 'centrifuge.io',
  'Goldfinch': 'goldfinch.finance',
  'Maple': 'maple.finance',
  'TrueFi': 'truefi.io',
  'Clearpool': 'clearpool.finance',
  'Ribbon': 'ribbon.finance',
  'StakeDAO': 'stakedao.org',
  'Convex': 'convexfinance.com',
  'Yearn': 'yearn.fi',
  'Beefy': 'beefy.com',
  'Autofarm': 'autofarm.network',
  'Harvest': 'harvest.finance',
  'Badger': 'badger.com',
  'Tokemak': 'tokemak.xyz',
  'Alchemix': 'alchemix.fi',
  'Liquity': 'liquity.org',
  'Reflexer': 'reflexer.finance',
  'Fei': 'fei.money',
  'Olympus': 'olympusdao.finance',
  'Wonderland': 'wonderland.money',
  'Klima': 'klimadao.finance',
  'Toucan': 'toucan.earth',
  'Moss': 'moss.earth',
  'KlimaDAO': 'klimadao.finance',
  'Gitcoin': 'gitcoin.co',
  'Clr.fund': 'clr.fund',
  'Dorahacks': 'dorahacks.io',
  'Giveth': 'giveth.io',
  'Gitcoin Grants': 'gitcoin.co',
  'Snapshot': 'snapshot.org',
  'Tally': 'tally.xyz',
  'Sybil': 'sybil.org',
  'Boardroom': 'boardroom.io',
  'Messari': 'messari.io',
  'Nansen': 'nansen.ai',
  'Dune': 'dune.com',
  'DeFi Llama': 'defillama.com',
  'Token Terminal': 'tokenterminal.com',
  'CryptoQuant': 'cryptoquant.com',
  'Glassnode': 'glassnode.com',
  'Santiment': 'santiment.net',
  'IntoTheBlock': 'intotheblock.com',
  'The Block': 'theblock.co',
  'CoinDesk': 'coindesk.com',
  'CoinTelegraph': 'cointelegraph.com',
  'Decrypt': 'decrypt.co',
  'Blockworks': 'blockworks.co',
  'Bankless': 'bankless.com',
  'The Defiant': 'thedefiant.io',
  'Unchained': 'unchainedcrypto.com',
  'What Bitcoin Did': 'whatbitcoindid.com',
  'The Pomp Podcast': 'pompcast.com',
  'Bankless Shows': 'bankless.com',
  'The Daily Gwei': 'thedailygwei.substack.com',
  'UpOnly': 'uponly.tv',
  'The Chopping Block': 'thechoppingblock.libsyn.com',
  'Uncommon Core': 'uncommoncore.co',
  'Bell Curve': 'bellcurve.mirror.xyz',
  'The Defi Podcast': 'thedefipodcast.com',
  'The Scoop': 'thescoop.co',
  'The Breakdown': 'breakdown.bitcoinmagazine.com',
  'Fed Watch': 'fedwatch.bitcoinmagazine.com',
  'On The Brink': 'onthebrinkpodcast.com',
  'Rabbit Hole Recap': 'rabbitholerecap.com',
  'The Money Movement': 'moneymovement.com',
  'The Block Experience': 'theblockexperience.io',
  'The Delphi Podcast': 'delphipodcast.com',
  'The Index Podcast': 'indexpodcast.com',
  'The Layer 2 Podcast': 'layer2podcast.com',
  'The Validator Podcast': 'validatorpodcast.com',
  'The Staking Podcast': 'stakingpodcast.com',
  'The MEV Podcast': 'mevpodcast.com',
  'The ZK Podcast': 'zkpodcast.com',
  'The Rollup': 'therollup.co',
  'The Daily ZK': 'dailyzk.com',
  'The zkSync Podcast': 'zksync.io',
  'The StarkNet Podcast': 'starknet.io',
  'The Polygon Podcast': 'polygon.technology',
  'The Arbitrum Podcast': 'arbitrum.io',
  'The Optimism Podcast': 'optimism.io',
  'The Base Podcast': 'base.org',
  'The Scroll Podcast': 'scroll.io',
  'The Linea Podcast': 'linea.build',
  'The Taiko Podcast': 'taiko.xyz',
  'The Eclipse Podcast': 'eclipse.builders',
  'The Celestia Podcast': 'celestia.org',
  'The EigenLayer Podcast': 'eigenlayer.xyz',
  'The Avail Podcast': 'availproject.org',
  'The Fuel Podcast': 'fuel.network',
  'The Monad Podcast': 'monad.xyz',
  'The Sei Podcast': 'sei.io',
  'The Aptos Podcast': 'aptoslabs.com',
  'The Sui Podcast': 'sui.io',
  'The Solana Podcast': 'solana.com',
  'The Near Podcast': 'near.org',
  'The Avalanche Podcast': 'avax.network',
  'The Cosmos Podcast': 'cosmos.network',
  'The Polkadot Podcast': 'polkadot.network',
  'The Kusama Podcast': 'kusama.network',
  'The Substrate Podcast': 'substrate.io',
  'The Ink Podcast': 'ink-lang.org',
  'The Cairo Podcast': 'cairo-lang.org',
  'The Noir Podcast': 'noir-lang.org',
  'The Leo Podcast': 'leo-lang.org',
  'The Move Podcast': 'move-language.github.io',
  'The Rust Podcast': 'rust-lang.org',
  'The Go Podcast': 'go.dev',
  'The Python Podcast': 'python.org',
  'The JavaScript Podcast': 'javascript.com',
  'The TypeScript Podcast': 'typescriptlang.org',
  'The React Podcast': 'react.dev',
  'The Vue Podcast': 'vuejs.org',
  'The Angular Podcast': 'angular.io',
  'The Svelte Podcast': 'svelte.dev',
  'The SolidJS Podcast': 'solidjs.com',
  'The Qwik Podcast': 'qwik.builder.io',
  'The Remix Podcast': 'remix.run',
  'The Next.js Podcast': 'nextjs.org',
  'The Nuxt Podcast': 'nuxt.com',
  'The Gatsby Podcast': 'gatsbyjs.com',
  'The Astro Podcast': 'astro.build',
  'The Eleventy Podcast': '11ty.dev',
  'The Hugo Podcast': 'gohugo.io',
  'The Jekyll Podcast': 'jekyllrb.com',
  'The Hexo Podcast': 'hexo.io',
  'The VuePress Podcast': 'vuepress.vuejs.org',
  'The Docusaurus Podcast': 'docusaurus.io',
  'The VitePress Podcast': 'vitepress.dev',
  'The MkDocs Podcast': 'mkdocs.org',
  'The GitBook Podcast': 'gitbook.com',
  'The ReadMe Podcast': 'readme.com',
  'The Stoplight Podcast': 'stoplight.io',
  'The Postman Podcast': 'postman.com',
  'The Insomnia Podcast': 'insomnia.rest',
  'The Hoppscotch Podcast': 'hoppscotch.io',
  'The Bruno Podcast': 'bruno.com',
  'The Kreya Podcast': 'kreya.app',
  'The Thunder Client Podcast': 'thunderclient.com',
  'The REST Client Podcast': 'restclient.io',
  'The HTTPie Podcast': 'httpie.io',
  'The curl Podcast': 'curl.se',
  'The wget Podcast': 'gnu.org',
  'The aria2 Podcast': 'aria2.github.io',
  'The yt-dlp Podcast': 'yt-dlp.org',
  'The ffmpeg Podcast': 'ffmpeg.org',
  'The ImageMagick Podcast': 'imagemagick.org',
  'The GraphicsMagick Podcast': 'graphicsmagick.org',
  'The Pillow Podcast': 'python-pillow.org',
  'The OpenCV Podcast': 'opencv.org',
  'The scikit-image Podcast': 'scikit-image.org',
  'The SimpleITK Podcast': 'simpleitk.org',
  'The ITK Podcast': 'itk.org',
  'The VTK Podcast': 'vtk.org',
  'The ParaView Podcast': 'paraview.org',
  'The Blender Podcast': 'blender.org',
  'The Maya Podcast': 'autodesk.com',
  'The 3ds Max Podcast': 'autodesk.com',
  'The Cinema 4D Podcast': 'maxon.net',
  'The Houdini Podcast': 'sidefx.com',
  'The Modo Podcast': 'foundry.com',
  'The ZBrush Podcast': 'maxon.net',
  'The Substance Podcast': 'adobe.com',
  'The Mari Podcast': 'foundry.com',
  'The Nuke Podcast': 'foundry.com',
  'The Fusion Podcast': 'blackmagicdesign.com',
  'The After Effects Podcast': 'adobe.com',
  'The Premiere Pro Podcast': 'adobe.com',
  'The DaVinci Resolve Podcast': 'blackmagicdesign.com',
  'The Final Cut Pro Podcast': 'apple.com',
  'The iMovie Podcast': 'apple.com',
  'The Filmora Podcast': 'wondershare.com',
  'The Camtasia Podcast': 'techsmith.com',
  'The OBS Podcast': 'obsproject.com',
  'The Streamlabs Podcast': 'streamlabs.com',
  'The XSplit Podcast': 'xsplit.com',
  'The vMix Podcast': 'vmix.com',
  'The Wirecast Podcast': 'telestream.net',
  'The Ecamm Live Podcast': 'ecamm.com',
  'The Restream Podcast': 'restream.io',
  'The StreamYard Podcast': 'streamyard.com',
  'The Riverside Podcast': 'riverside.fm',
  'The SquadCast Podcast': 'squadcast.fm',
  'The Zencastr Podcast': 'zencastr.com',
  'The Anchor Podcast': 'anchor.fm',
  'The Buzzsprout Podcast': 'buzzsprout.com',
  'The Libsyn Podcast': 'libsyn.com',
  'The Podbean Podcast': 'podbean.com',
  'The Transistor Podcast': 'transistor.fm',
  'The Simplecast Podcast': 'simplecast.com',
  'The Captivate Podcast': 'captivate.fm',
  'The Castos Podcast': 'castos.com',
  'The Fusebox Podcast': 'fusebox.fm',
  'The Seriously Simple Podcasting': 'seriouslysimplepodcasting.com',
  'The PowerPress Podcast': 'powerpress.com',
  'The Blubrry Podcast': 'blubrry.com',
  'The Podlove Podcast': 'podlove.org',
  'The WordPress Podcast': 'wordpress.org',
  'The Ghost Podcast': 'ghost.org',
  'The Medium Podcast': 'medium.com',
  'The Substack Podcast': 'substack.com',
  'The Revue Podcast': 'revue.co',
  'The Buttondown Podcast': 'buttondown.email',
  'The ConvertKit Podcast': 'convertkit.com',
  'The Mailchimp Podcast': 'mailchimp.com',
  'The MailerLite Podcast': 'mailerlite.com',
  'The Sendinblue Podcast': 'sendinblue.com',
  'The ActiveCampaign Podcast': 'activecampaign.com',
  'The HubSpot Podcast': 'hubspot.com',
  'The Salesforce Podcast': 'salesforce.com',
  'The Pipedrive Podcast': 'pipedrive.com',
  'The Zoho Podcast': 'zoho.com',
  'The Freshworks Podcast': 'freshworks.com',
  'The Zendesk Podcast': 'zendesk.com',
  'The Intercom Podcast': 'intercom.com',
  'The Drift Podcast': 'drift.com',
  'The Crisp Podcast': 'crisp.chat',
  'The Tidio Podcast': 'tidio.com',
  'The LiveChat Podcast': 'livechat.com',
  'The Olark Podcast': 'olark.com',
  'The Pure Chat Podcast': 'purechat.com',
  'The Tawk.to Podcast': 'tawk.to',
  'The Chatra Podcast': 'chatra.io',
  'The Chaport Podcast': 'chaport.com',
  'The JivoChat Podcast': 'jivochat.com',
  'The Smartsupp Podcast': 'smartsupp.com',
  'The Userlike Podcast': 'userlike.com',
  'The SnapEngage Podcast': 'snapengage.com',
  'The ClickDesk Podcast': 'clickdesk.com',
  'The Comm100 Podcast': 'comm100.com',
  'The Provide Support Podcast': 'provide-support.com',
  'The Kayako Podcast': 'kayako.com',
  'The Groove Podcast': 'groovehq.com',
  'The Help Scout Podcast': 'helpscout.com',
  'The Front Podcast': 'front.com',
  'The Missive Podcast': 'missiveapp.com',
  'The SparkPost Podcast': 'sparkpost.com',
  'The SendGrid Podcast': 'sendgrid.com',
  'The Mailgun Podcast': 'mailgun.com',
  'The Postmark Podcast': 'postmarkapp.com',
  'The Amazon SES Podcast': 'aws.amazon.com',
  'The Mandrill Podcast': 'mandrill.com',
  'The Mailjet Podcast': 'mailjet.com',
  'The Elastic Email Podcast': 'elasticemail.com',
  'The Pepipost Podcast': 'pepipost.com',
  'The Netcore Podcast': 'netcorecloud.com',
  'The MoEngage Podcast': 'moengage.com',
  'The CleverTap Podcast': 'clevertap.com',
  'The Braze Podcast': 'braze.com',
  'The Airship Podcast': 'airship.com',
  'The OneSignal Podcast': 'onesignal.com',
  'The Pushwoosh Podcast': 'pushwoosh.com',
  'The Firebase Cloud Messaging Podcast': 'firebase.google.com',
  'The Pusher Podcast': 'pusher.com',
  'The Ably Podcast': 'ably.com',
  'The PubNub Podcast': 'pubnub.com',
  'The Stream Podcast': 'getstream.io',
  'The Twilio Podcast': 'twilio.com',
  'The Vonage Podcast': 'vonage.com',
  'The MessageBird Podcast': 'messagebird.com',
  'The Plivo Podcast': 'plivo.com',
  'The Bandwidth Podcast': 'bandwidth.com',
  'The Telnyx Podcast': 'telnyx.com',
  'The Sinch Podcast': 'sinch.com',
  'The Infobip Podcast': 'infobip.com',
  'The CM.com Podcast': 'cm.com',
  'The Sendbird Podcast': 'sendbird.com',
  'The Stream Chat Podcast': 'getstream.io',
  'The TalkJS Podcast': 'talkjs.com',
  'The Chatkit Podcast': 'pusher.com',
  'The CometChat Podcast': 'cometchat.com',
  'The MirrorFly Podcast': 'mirrorfly.com',
  'The Applozic Podcast': 'applozic.com',
  'The QuickBlox Podcast': 'quickblox.com',
  'The ConnectyCube Podcast': 'connectycube.com',
  'The Sinch Chatlayer Podcast': 'sinch.com',
  'The Rasa Podcast': 'rasa.com',
  'The Dialogflow Podcast': 'cloud.google.com',
  'The Watson Assistant Podcast': 'ibm.com',
  'The Amazon Lex Podcast': 'aws.amazon.com',
  'The Microsoft Bot Framework Podcast': 'microsoft.com',
  'The Botpress Podcast': 'botpress.com',
  'The Stack AI Podcast': 'stack-ai.com',
  'The Voiceflow Podcast': 'voiceflow.com',
  'The Botmock Podcast': 'botmock.com',
  'The Botsociety Podcast': 'botsociety.io',
  'The Figma Plugins Podcast': 'figma.com',
  'The Sketch Plugins Podcast': 'sketch.com',
  'The Adobe XD Plugins Podcast': 'adobe.com',
  'The Chrome Extensions Podcast': 'chrome.google.com',
  'The VS Code Extensions Podcast': 'code.visualstudio.com',
  'The JetBrains Plugins Podcast': 'jetbrains.com',
  'The Vim Plugins Podcast': 'vim.org',
  'The Emacs Packages Podcast': 'gnu.org',
  'The Sublime Text Packages Podcast': 'sublimetext.com',
  'The Atom Packages Podcast': 'atom.io',
  'The Nova Extensions Podcast': 'nova.app',
  'The Coda Plugins Podcast': 'coda.io',
  'The Panic Nova Podcast': 'nova.app',
  'The Tower Podcast': 'git-tower.com',
  'The Fork Podcast': 'fork.dev',
  'The Sourcetree Podcast': 'sourcetreeapp.com',
  'The GitKraken Podcast': 'gitkraken.com',
  'The SmartGit Podcast': 'syntevo.com',
  'The GitHub Desktop Podcast': 'github.com',
  'The Gitpod Podcast': 'gitpod.io',
  'The Codespaces Podcast': 'github.com',
  'The CodeSandbox Podcast': 'codesandbox.io',
  'The StackBlitz Podcast': 'stackblitz.com',
  'The Glitch Podcast': 'glitch.com',
  'The Repl.it Podcast': 'replit.com',
  'The Jupyter Notebook Podcast': 'jupyter.org',
  'The Google Colab Podcast': 'colab.research.google.com',
  'The Kaggle Notebooks Podcast': 'kaggle.com',
  'The Deepnote Podcast': 'deepnote.com',
  'The Hex Podcast': 'hex.tech',
  'The Observable Podcast': 'observablehq.com',
  'The D3.js Podcast': 'd3js.org',
  'The Chart.js Podcast': 'chartjs.org',
  'The Plotly Podcast': 'plotly.com',
  'The Highcharts Podcast': 'highcharts.com',
  'The ECharts Podcast': 'echarts.apache.org',
  'The Apache ECharts Podcast': 'echarts.apache.org',
  'The AntV Podcast': 'antv.vision',
  'The Visx Podcast': 'airbnb.io',
  'The Nivo Podcast': 'nivo.rocks',
  'The Recharts Podcast': 'recharts.org',
  'The Victory Podcast': 'formidable.com',
  'The React-Vis Podcast': 'uber.github.io',
  'The Semiotic Podcast': 'semiotic.nteract.io',
  'The Vega Podcast': 'vega.github.io',
  'The Vega-Lite Podcast': 'vega.github.io',
  'The Altair Podcast': 'altair-viz.github.io',
  'The Bokeh Podcast': 'bokeh.org',
  'The HoloViews Podcast': 'holoviews.org',
  'The Panel Podcast': 'panel.holoviz.org',
  'The Streamlit Podcast': 'streamlit.io',
  'The Gradio Podcast': 'gradio.app',
  'The Dash Podcast': 'plotly.com',
  'The Shiny Podcast': 'shiny.rstudio.com',
  'The Voilà Podcast': 'voila-gallery.org',
  'The Mercury Podcast': 'mljar.com',
  'The Anvil Podcast': 'anvil.works',
  'The PyWebIO Podcast': 'pywebio.readthedocs.io',
  'The NiceGUI Podcast': 'nicegui.io',
  'The Flet Podcast': 'flet.dev',
  'The Reflex Podcast': 'reflex.dev',
  'The Solara Podcast': 'solara.dev',
  'The HoloViz Podcast': 'holoviz.org',
  'The Datashader Podcast': 'datashader.org',
  'The Colorcet Podcast': 'colorcet.holoviz.org',
  'The Param Podcast': 'param.holoviz.org',
  'The PyViz Podcast': 'pyviz.org',
  'The GeoViews Podcast': 'geoviews.org',
  'The EarthSim Podcast': 'earthsim.pyviz.org',
  'The Cartopy Podcast': 'scitools.org.uk',
  'The Basemap Podcast': 'matplotlib.org',
  'The GeoPandas Podcast': 'geopandas.org',
  'The Shapely Podcast': 'shapely.readthedocs.io',
  'The Fiona Podcast': 'fiona.readthedocs.io',
  'The Rasterio Podcast': 'rasterio.readthedocs.io',
  'The Xarray Podcast': 'xarray.dev',
  'The Iris Podcast': 'scitools.org.uk',
  'The MetPy Podcast': 'unidata.github.io',
  'The Siphon Podcast': 'unidata.github.io',
  'The Pint Podcast': 'pint.readthedocs.io',
  'The Quantities Podcast': 'python-quantities.readthedocs.io',
  'The Astropy Podcast': 'astropy.org',
  'The SunPy Podcast': 'sunpy.org',
  'The SpacePy Podcast': 'spacepy.github.io',
  'The PlasmaPy Podcast': 'plasmapy.org',
  'The yt Podcast': 'yt-project.org',
  'The VisIt Podcast': 'visit.llnl.gov',
  'The VMD Podcast': 'ks.uiuc.edu',
  'The PyMOL Podcast': 'pymol.org',
  'The ChimeraX Podcast': 'cgl.ucsf.edu',
  'The Molsoft Podcast': 'molsoft.com',
  'The Schrödinger Podcast': 'schrodinger.com',
  'The OpenEye Podcast': 'eyesopen.com',
  'The CCG Podcast': 'chemcomp.com',
  'The MOE Podcast': 'chemcomp.com',
  'The Discovery Studio Podcast': 'biovia.com',
  'The Maestro Podcast': 'schrodinger.com',
  'The KNIME Podcast': 'knime.com',
  'The RapidMiner Podcast': 'rapidminer.com',
  'The Alteryx Podcast': 'alteryx.com',
  'The Dataiku Podcast': 'dataiku.com',
  'The Databricks Podcast': 'databricks.com',
  'The Snowflake Podcast': 'snowflake.com',
  'The BigQuery Podcast': 'cloud.google.com',
  'The Redshift Podcast': 'aws.amazon.com',
  'The Azure Synapse Podcast': 'azure.microsoft.com',
  'The Databricks SQL Podcast': 'databricks.com',
  'The Presto Podcast': 'prestodb.io',
  'The Trino Podcast': 'trino.io',
  'The ClickHouse Podcast': 'clickhouse.com',
  'The Druid Podcast': 'druid.apache.org',
  'The Pinot Podcast': 'pinot.apache.org',
  'The Kylin Podcast': 'kylin.apache.org',
  'The Superset Podcast': 'superset.apache.org',
  'The Metabase Podcast': 'metabase.com',
  'The Grafana Podcast': 'grafana.com',
  'The Kibana Podcast': 'elastic.co',
  'The Tableau Podcast': 'tableau.com',
  'The Power BI Podcast': 'microsoft.com',
  'The Looker Podcast': 'looker.com',
  'The Mode Analytics Podcast': 'mode.com',
  'The Periscope Data Podcast': 'periscopedata.com',
  'The Chartio Podcast': 'chartio.com',
  'The Redash Podcast': 'redash.io',
  'The Preset Podcast': 'preset.io',
  'The Lightdash Podcast': 'lightdash.com',
  'The Evidence Podcast': 'evidence.dev',
  'The Observable Plot Podcast': 'observablehq.com',
  'The Three.js Podcast': 'threejs.org',
  'The Babylon.js Podcast': 'babylonjs.com',
  'The PlayCanvas Podcast': 'playcanvas.com',
  'The A-Frame Podcast': 'aframe.io',
  'The WebXR Podcast': 'immersiveweb.dev',
  'The WebGL Podcast': 'khronos.org',
  'The OpenGL Podcast': 'khronos.org',
  'The Vulkan Podcast': 'khronos.org',
  'The Metal Podcast': 'apple.com',
  'The DirectX Podcast': 'microsoft.com',
  'The CUDA Podcast': 'nvidia.com',
  'The OpenCL Podcast': 'khronos.org',
  'The ROCm Podcast': 'amd.com',
  'The oneAPI Podcast': 'intel.com',
  'The SYCL Podcast': 'khronos.org',
  'The OpenMP Podcast': 'openmp.org',
  'The MPI Podcast': 'mpi-forum.org',
  'The OpenACC Podcast': 'openacc.org',
  'The Kokkos Podcast': 'kokkos.github.io',
  'The Raja Podcast': 'llnl.gov',
  'The Umpire Podcast': 'llnl.gov',
  'The CHAI Podcast': 'llnl.gov',
  'The Axom Podcast': 'llnl.gov',
  'The Conduit Podcast': 'llnl.gov',
  'The Ascent Podcast': 'llnl.gov',
  'The VTK-m Podcast': 'm.vtk.org',
  'The Cabana Podcast': 'ornl.gov',
  'The Heffte Podcast': 'ornl.gov',
  'The SLATE Podcast': 'ornl.gov',
  'The DPLASMA Podcast': 'icl.utk.edu',
  'The PaRSEC Podcast': 'icl.utk.edu',
  'The StarPU Podcast': 'starpu.gforge.inria.fr',
  'The OmpSs Podcast': 'pm.bsc.es',
  'The Legion Podcast': 'legion.stanford.edu',
  'The Regent Podcast': 'regent-lang.org',
  'The Charm++ Podcast': 'charmplusplus.org',
  'The HPX Podcast': 'hpx.stellar-group.org',
  'The UPC++ Podcast': 'upcxx.lbl.gov',
  'The GASNet Podcast': 'gasnet.lbl.gov',
  'The OpenSHMEM Podcast': 'openshmem.org',
  'The MPI Forum Podcast': 'mpi-forum.org',
  'The OpenMP ARB Podcast': 'openmp.org',
  'The Khronos Group Podcast': 'khronos.org',
  'The WebAssembly Podcast': 'webassembly.org',
  'The WASI Podcast': 'wasi.dev',
  'The Wasmtime Podcast': 'wasmtime.dev',
  'The WAMR Podcast': 'github.com',
  'The WasmEdge Podcast': 'wasmedge.org',
  'The Fermyon Podcast': 'fermyon.com',
  'The Spin Podcast': 'fermyon.com',
  'The Slight Podcast': 'deislabs.io',
  'The WasmCloud Podcast': 'wasmcloud.com',
  'The Cosmonic Podcast': 'cosmonic.com',
  'The Suborbital Podcast': 'suborbital.dev',
  'The Atmo Podcast': 'suborbital.dev',
  'The Sat Podcast': 'suborbital.dev',
  'The Wagi Podcast': 'deislabs.io',
  'The Hippo Podcast': 'deislabs.io',
  'The Bindle Podcast': 'deislabs.io',
  'The Krustlet Podcast': 'krustlet.dev',
  'The KubeEdge Podcast': 'kubeedge.io',
  'The OpenYurt Podcast': 'openyurt.io',
  'The SuperEdge Podcast': 'superedge.io',
  'The EdgeX Foundry Podcast': 'edgexfoundry.org',
  'The Fledge Podcast': 'fledge-iot.org',
  'The ThingsBoard Podcast': 'thingsboard.io',
  'The Node-RED Podcast': 'nodered.org',
  'The Home Assistant Podcast': 'home-assistant.io',
  'The OpenHAB Podcast': 'openhab.org',
  'The Domoticz Podcast': 'domoticz.com',
  'The ioBroker Podcast': 'iobroker.net',
  'The Homey Podcast': 'homey.app',
  'The SmartThings Podcast': 'smartthings.com',
  'The Hubitat Podcast': 'hubitat.com',
  'The Wink Podcast': 'wink.com',
  'The Insteon Podcast': 'insteon.com',
  'The Lutron Podcast': 'lutron.com',
  'The Philips Hue Podcast': 'philips-hue.com',
  'The Nanoleaf Podcast': 'nanoleaf.me',
  'The LIFX Podcast': 'lifx.com',
  'The Yeelight Podcast': 'yeelight.com',
  'The TP-Link Kasa Podcast': 'tp-link.com',
  'The Wyze Podcast': 'wyze.com',
  'The Ring Podcast': 'ring.com',
  'The Nest Podcast': 'nest.com',
  'The Ecobee Podcast': 'ecobee.com',
  'The Honeywell Home Podcast': 'honeywellhome.com',
  'The August Podcast': 'august.com',
  'The Yale Podcast': 'yalehome.com',
  'The Schlage Podcast': 'schlage.com',
  'The Kwikset Podcast': 'kwikset.com',
  'The Level Podcast': 'level.co',
  'The Lockly Podcast': 'lockly.com',
  'The Ultraloq Podcast': 'ultraloq.com',
  'The Eufy Podcast': 'eufy.com',
  'The Arlo Podcast': 'arlo.com',
  'The Blink Podcast': 'blinkforhome.com',
  'The Reolink Podcast': 'reolink.com',
  'The Amcrest Podcast': 'amcrest.com',
  'The Swann Podcast': 'swann.com',
  'The Lorex Podcast': 'lorex.com',
  'The Night Owl Podcast': 'nightowlsp.com',
  'The Zmodo Podcast': 'zmodo.com',
  'The Annke Podcast': 'annke.com',
  'The Hikvision Podcast': 'hikvision.com',
  'The Dahua Podcast': 'dahuatech.com',
  'The Axis Podcast': 'axis.com',
  'The Bosch Podcast': 'boschsecurity.com',
  'The Hanwha Podcast': 'hanwhasecurity.com',
  'The Avigilon Podcast': 'avigilon.com',
  'The Genetec Podcast': 'genetec.com',
  'The Milestone Podcast': 'milestonesys.com',
  'The Exacq Podcast': 'exacq.com',
  'The DVTel Podcast': 'dvtel.com',
  'The FLIR Podcast': 'flir.com',
  'The Pelco Podcast': 'pelco.com',
  'The IndigoVision Podcast': 'indigovision.com',
  'The March Networks Podcast': 'marchnetworks.com',
  'The Verkada Podcast': 'verkada.com',
  'The Rhombus Podcast': 'rhombus.com',
  'The Eagle Eye Networks Podcast': 'eagleeyenetworks.com',
  'The Brivo Podcast': 'brivo.com',
  'The Kantech Podcast': 'kantech.com',
  'The Paxton Podcast': 'paxton.co.uk',
  'The HID Global Podcast': 'hidglobal.com',
  'The Allegion Podcast': 'allegion.com',
  'The Assa Abloy Podcast': 'assaabloy.com',
  'The Dormakaba Podcast': 'dormakaba.com',
  'The Stanley Podcast': 'stanleysecurity.com',
  'The Johnson Controls Podcast': 'johnsoncontrols.com',
  'The Siemens Podcast': 'siemens.com',
  'The Honeywell Podcast': 'honeywell.com',
  'The Panasonic Podcast': 'panasonic.com',
  'The Sony Podcast': 'sony.com',
  'The Samsung Podcast': 'samsung.com',
  'The LG Podcast': 'lg.com',
  'The Philips Podcast': 'philips.com',
  'The Osram Podcast': 'osram.com',
  'The Cree Podcast': 'cree.com',
  'The GE Podcast': 'ge.com',
  'The Sylvania Podcast': 'sylvania.com',
  'The TCP Podcast': 'tcplighting.com',
  'The Feit Electric Podcast': 'feit.com',
  'The Sengled Podcast': 'sengled.com',
  'The Globe Electric Podcast': 'globe-electric.com',
  'The Merkury Podcast': 'merkuryinnovations.com',
  'The Treatlife Podcast': 'treatlife.tech',
  'The Gosund Podcast': 'gosund.com',
  'The Teckin Podcast': 'teckinhome.com',
  'The Kasa Podcast': 'kasa.com',
  'The Tapo Podcast': 'tapo.com',
  'The Meross Podcast': 'meross.com',
  'The Aqara Podcast': 'aqara.com',
  'The Tuya Podcast': 'tuya.com',
  'The Smart Life Podcast': 'smartlife.com',
  'The eWeLink Podcast': 'ewelink.cc',
  'The Broadlink Podcast': 'broadlink.com.cn',
  'The Sonoff Podcast': 'sonoff.tech',
  'The Shelly Podcast': 'shelly.cloud',
  'The Tasmota Podcast': 'tasmota.com',
  'The ESPHome Podcast': 'esphome.io',
  'The WLED Podcast': 'kno.wled.ge',
  'The Hyperion Podcast': 'hyperion-project.org',
  'The Ambilight Podcast': 'philips.com',
  'The ScreenBloom Podcast': 'screenbloom.com',
  'The Prismatik Podcast': 'woodenshark.com',
  'The Lightpack Podcast': 'lightpack.tv',
  'The Adalight Podcast': 'adafruit.com',
  'The Boblight Podcast': 'boblight.googlecode.com',
  'The AtmoWin Podcast': 'atmo-win.de',
  'The AmbiBox Podcast': 'ambibox.ru',
  'The PulseAudio Podcast': 'pulseaudio.org',
  'The PipeWire Podcast': 'pipewire.org',
  'The ALSA Podcast': 'alsa-project.org',
  'The JACK Podcast': 'jackaudio.org',
  'The PortAudio Podcast': 'portaudio.com',
  'The RtAudio Podcast': 'music.mcgill.ca',
  'The SoundIo Podcast': 'libsound.io',
  'The Miniaudio Podcast': 'miniaud.io',
  'The SoLoud Podcast': 'soloud-audio.com',
  'The OpenAL Podcast': 'openal.org',
  'The FMOD Podcast': 'fmod.com',
  'The Wwise Podcast': 'audiokinetic.com',
  'The Steam Audio Podcast': 'valvesoftware.com',
  'The Resonance Audio Podcast': 'resonance-audio.io',
  'The Google VR Audio Podcast': 'developers.google.com',
  'The Oculus Audio SDK Podcast': 'developer.oculus.com',
  'The Microsoft Spatial Sound Podcast': 'microsoft.com',
  'The Dolby Atmos Podcast': 'dolby.com',
  'The DTS:X Podcast': 'dts.com',
  'The Auro-3D Podcast': 'auro-3d.com',
  'The MPEG-H Podcast': 'mpeg.chiariglione.org',
  'The AC-4 Podcast': 'dolby.com',
  'The Opus Podcast': 'opus-codec.org',
  'The Vorbis Podcast': 'xiph.org',
  'The FLAC Podcast': 'xiph.org',
  'The ALAC Podcast': 'apple.com',
  'The WavPack Podcast': 'wavpack.com',
  'The Monkey Audio Podcast': 'monkeysaudio.com',
  'The TTA Podcast': 'tta.sourceforge.net',
  'The TAK Podcast': 'tak.sourceforge.net',
  'The OptimFROG Podcast': 'optimfrog.com',
  'The Shorten Podcast': 'etree.org',
  'The LPAC Podcast': 'lpac.sourceforge.net',
  'The MPEG-1 Podcast': 'mpeg.chiariglione.org',
  'The MPEG-2 Podcast': 'mpeg.chiariglione.org',
  'The MPEG-4 Podcast': 'mpeg.chiariglione.org',
  'The H.264 Podcast': 'h264.com',
  'The H.265 Podcast': 'h265.com',
  'The AV1 Podcast': 'aomedia.org',
  'The VP9 Podcast': 'webmproject.org',
  'The VP8 Podcast': 'webmproject.org',
  'The Theora Podcast': 'theora.org',
  'The Daala Podcast': 'xiph.org',
  'The Thor Podcast': 'thor.codec.org',
  'The Dirac Podcast': 'diracvideo.org',
  'The x264 Podcast': 'videolan.org',
  'The x265 Podcast': 'videolan.org',
  'The SVT-AV1 Podcast': 'gitlab.com',
  'The rav1e Podcast': 'github.com',
  'The AOMedia Podcast': 'aomedia.org',
  'The Alliance for Open Media Podcast': 'aomedia.org',
  'The WebM Podcast': 'webmproject.org',
  'The Matroska Podcast': 'matroska.org',
  'The MP4 Podcast': 'mp4ra.org',
  'The QuickTime Podcast': 'apple.com',
  'The AVI Podcast': 'microsoft.com',
  'The WMV Podcast': 'microsoft.com',
  'The FLV Podcast': 'adobe.com',
  'The SWF Podcast': 'adobe.com',
  'The RTMP Podcast': 'adobe.com',
  'The RTSP Podcast': 'rtsp.org',
  'The RTP Podcast': 'ietf.org',
  'The SRTP Podcast': 'ietf.org',
  'The ZRTP Podcast': 'zfoneproject.com',
  'The DTLS Podcast': 'ietf.org',
  'The TLS Podcast': 'ietf.org',
  'The SSL Podcast': 'ietf.org',
  'The HTTPS Podcast': 'ietf.org',
  'The HTTP/2 Podcast': 'ietf.org',
  'The HTTP/3 Podcast': 'ietf.org',
  'The QUIC Podcast': 'ietf.org',
  'The UDP Podcast': 'ietf.org',
  'The SCTP Podcast': 'ietf.org',
  'The DCCP Podcast': 'ietf.org',
  'The RSVP Podcast': 'ietf.org',
  'The MPLS Podcast': 'ietf.org',
  'The LDP Podcast': 'ietf.org',
  'The BGP Podcast': 'ietf.org',
  'The OSPF Podcast': 'ietf.org',
  'The IS-IS Podcast': 'ietf.org',
  'The EIGRP Podcast': 'cisco.com',
  'The RIP Podcast': 'ietf.org',
  'The IGMP Podcast': 'ietf.org',
  'The PIM Podcast': 'ietf.org',
  'The MSDP Podcast': 'ietf.org',
  'The VXLAN Podcast': 'ietf.org',
  'The NVGRE Podcast': 'ietf.org',
  'The STT Podcast': 'ietf.org',
  'The Geneve Podcast': 'ietf.org',
  'The GRE Podcast': 'ietf.org',
  'The IPsec Podcast': 'ietf.org',
  'The IKEv2 Podcast': 'ietf.org',
  'The L2TP Podcast': 'ietf.org',
  'The PPTP Podcast': 'microsoft.com',
  'The OpenVPN Podcast': 'openvpn.net',
  'The WireGuard Podcast': 'wireguard.com',
  'The StrongSwan Podcast': 'strongswan.org',
  'The Libreswan Podcast': 'libreswan.org',
  'The Racoon Podcast': 'racoon2.wide.ad.jp',
  'The Openswan Podcast': 'openswan.org',
  'The Tinc Podcast': 'tinc-vpn.org',
  'The ZeroTier Podcast': 'zerotier.com',
  'The Tailscale Podcast': 'tailscale.com',
  'The Headscale Podcast': 'headscale.net',
  'The Nebula Podcast': 'github.com',
  'The Innernet Podcast': 'innernet.dev',
  'The Netbird Podcast': 'netbird.io',
  'The Netmaker Podcast': 'netmaker.io',
  'The Pritunl Podcast': 'pritunl.com',
  'The Algo Podcast': 'github.com',
  'The Streisand Podcast': 'github.com',
  'The Outline Podcast': 'getoutline.org',
  'The Shadowsocks Podcast': 'shadowsocks.org',
  'The V2Ray Podcast': 'v2ray.com',
  'The Trojan Podcast': 'trojan-gfw.github.io',
  'The Xray Podcast': 'xtls.github.io',
  'The Hysteria Podcast': 'hysteria.network',
  'The Tuic Podcast': 'github.com',
  'The Reality Podcast': 'github.com',
  'The gRPC Podcast': 'grpc.io',
  'The Thrift Podcast': 'thrift.apache.org',
  'The Avro Podcast': 'avro.apache.org',
  'The Protocol Buffers Podcast': 'protobuf.dev',
  'The FlatBuffers Podcast': 'flatbuffers.dev',
  'The Capn Proto Podcast': 'capnproto.org',
  'The MessagePack Podcast': 'msgpack.org',
  'The BSON Podcast': 'bsonspec.org',
  'The CBOR Podcast': 'cbor.io',
  'The Smile Podcast': 'github.com',
  'The Ion Podcast': 'amazon.com',
  'The Parquet Podcast': 'parquet.apache.org',
  'The ORC Podcast': 'orc.apache.org',
  'The Arrow Podcast': 'arrow.apache.org',
  'The Feather Podcast': 'arrow.apache.org',
  'The Delta Lake Podcast': 'delta.io',
  'The Iceberg Podcast': 'iceberg.apache.org',
  'The Hudi Podcast': 'hudi.apache.org',
  'The Paimon Podcast': 'paimon.apache.org',
  'The Hive Podcast': 'hive.apache.org',
  'The HBase Podcast': 'hbase.apache.org',
  'The Cassandra Podcast': 'cassandra.apache.org',
  'The ScyllaDB Podcast': 'scylladb.com',
  'The YugabyteDB Podcast': 'yugabyte.com',
  'The CockroachDB Podcast': 'cockroachlabs.com',
  'The TiDB Podcast': 'pingcap.com',
  'The Vitess Podcast': 'vitess.io',
  'The PlanetScale Podcast': 'planetscale.com',
  'The Neon Podcast': 'neon.tech',
  'The Supabase Podcast': 'supabase.com',
  'The Xata Podcast': 'xata.io',
  'The Fauna Podcast': 'fauna.com',
  'The Convex Podcast': 'convex.dev',
  'The Replicache Podcast': 'replicache.dev',
  'The Electric SQL Podcast': 'electric-sql.com',
  'The PowerSync Podcast': 'powersync.com',
  'The TinyBase Podcast': 'tinybase.org',
  'The RxDB Podcast': 'rxdb.info',
  'The WatermelonDB Podcast': 'watermelondb.dev',
  'The ObjectBox Podcast': 'objectbox.io',
  'The Realm Podcast': 'mongodb.com',
  'The Couchbase Podcast': 'couchbase.com',
  'The PouchDB Podcast': 'pouchdb.com',
  'The Hoodie Podcast': 'hood.ie',
  'The Kinto Podcast': 'kinto.readthedocs.io',
  'The RemoteStorage Podcast': 'remotestorage.io',
  'The Solid Podcast': 'solidproject.org',
  'The Inrupt Podcast': 'inrupt.com',
  'The Nextcloud Podcast': 'nextcloud.com',
  'The ownCloud Podcast': 'owncloud.com',
  'The Seafile Podcast': 'seafile.com',
  'The Pydio Podcast': 'pydio.com',
  'The Syncthing Podcast': 'syncthing.net',
  'The Resilio Podcast': 'resilio.com',
  'The Dropbox Podcast': 'dropbox.com',
  'The Google Drive Podcast': 'google.com',
  'The OneDrive Podcast': 'microsoft.com',
  'The iCloud Podcast': 'apple.com',
  'The Box Podcast': 'box.com',
  'The pCloud Podcast': 'pcloud.com',
  'The Mega Podcast': 'mega.nz',
  'The MediaFire Podcast': 'mediafire.com',
  'The WeTransfer Podcast': 'wetransfer.com',
  'The SendAnywhere Podcast': 'send-anywhere.com',
  'The Shareit Podcast': 'ushareit.com',
  'The Xender Podcast': 'xender.com',
  'The Zapya Podcast': 'izapya.com',
  'The SHAREit Podcast': 'ushareit.com',
  'The Files by Google Podcast': 'google.com',
  'The ES File Explorer Podcast': 'estrongs.com',
  'The Solid Explorer Podcast': 'solidexplorer.com',
  'The FX File Explorer Podcast': 'nextapp.com',
  'The MiXplorer Podcast': 'mixplorer.com',
  'The Amaze File Manager Podcast': 'teamamaze.xyz',
  'The Simple Gallery Podcast': 'simplemobiletools.com',
  'The Aves Podcast': 'github.com',
  'The F-Stop Podcast': 'fstopapp.com',
  'The QuickPic Podcast': 'github.com',
  'The Piktures Podcast': 'piktures.app',
  'The Google Photos Podcast': 'google.com',
  'The Amazon Photos Podcast': 'amazon.com',
  'The Flickr Podcast': 'flickr.com',
  'The 500px Podcast': '500px.com',
  'The Unsplash Podcast': 'unsplash.com',
  'The Pexels Podcast': 'pexels.com',
  'The Pixabay Podcast': 'pixabay.com',
  'The Burst Podcast': 'burst.shopify.com',
  'The StockSnap Podcast': 'stocksnap.io',
  'The Gratisography Podcast': 'gratisography.com',
  'The Picjumbo Podcast': 'picjumbo.com',
  'The Kaboompics Podcast': 'kaboompics.com',
  'The Life of Pix Podcast': 'lifeofpix.com',
  'The SplitShire Podcast': 'splitshire.com',
  'The Startup Stock Photos Podcast': 'startupstockphotos.com',
  'The Jay Mantri Podcast': 'jaymantri.com',
  'The MMT Podcast': 'mmtstock.com',
  'The Negative Space Podcast': 'negativespace.co',
  'The Death to Stock Podcast': 'deathtothestockphoto.com',
  'The Refe Podcast': 'refe.it',
  'The Moveast Podcast': 'moveast.me',
  'The Travel Coffee Book Podcast': 'travelcoffeebook.com',
  'The Snapwire Snaps Podcast': 'snapwi.re',
  'The Tookapic Podcast': 'tookapic.com',
  'The Fancycrave Podcast': 'fancycrave.com',
  'The Stockvault Podcast': 'stockvault.net',
  'The FreeImages Podcast': 'freeimages.com',
  'The RGBStock Podcast': 'rgbstock.com',
  'The Morguefile Podcast': 'morguefile.com',
  'The ImageAfter Podcast': 'imageafter.com',
  'The Everystockphoto Podcast': 'everystockphoto.com',
  'The Photo Rack Podcast': 'photorack.net',
  'The Public Domain Pictures Podcast': 'publicdomainpictures.net',
  'The PDPhoto Podcast': 'pdphoto.org',
  'The Wikimedia Commons Podcast': 'commons.wikimedia.org',
  'The Internet Archive Podcast': 'archive.org',
  'The Library of Congress Podcast': 'loc.gov',
  'The NASA Images Podcast': 'images.nasa.gov',
  'The NOAA Photo Library Podcast': 'photolib.noaa.gov',
  'The USGS Multimedia Gallery Podcast': 'gallery.usgs.gov',
  'The NIH Image Gallery Podcast': 'images.nih.gov',
  'The CDC Public Health Image Library Podcast': 'phil.cdc.gov',
  'The NIAID Flickr Podcast': 'flickr.com',
  'The Wellcome Collection Podcast': 'wellcomecollection.org',
  'The Europeana Podcast': 'europeana.eu',
  'The Digital Public Library of America Podcast': 'dp.la',
  'The National Archives Podcast': 'archives.gov',
  'The Smithsonian Podcast': 'si.edu',
  'The Getty Podcast': 'getty.edu',
  'The Met Podcast': 'metmuseum.org',
  'The British Museum Podcast': 'britishmuseum.org',
  'The Louvre Podcast': 'louvre.fr',
  'The Rijksmuseum Podcast': 'rijksmuseum.nl',
  'The Uffizi Podcast': 'uffizi.it',
  'The Prado Podcast': 'museodelprado.es',
  'The Hermitage Podcast': 'hermitagemuseum.org',
  'The Vatican Museums Podcast': 'museivaticani.va',
  'The Acropolis Museum Podcast': 'theacropolismuseum.gr',
  'The National Palace Museum Podcast': 'npm.gov.tw',
  'The Tokyo National Museum Podcast': 'tnm.jp',
  'The Kyoto National Museum Podcast': 'kyohaku.go.jp',
  'The Nara National Museum Podcast': 'narahaku.go.jp',
  'The National Museum of Korea Podcast': 'museum.go.kr',
  'The National Museum of China Podcast': 'chnmuseum.cn',
  'The Palace Museum Podcast': 'dpm.org.cn',
  'The Shanghai Museum Podcast': 'shanghaimuseum.net',
  'The Nanjing Museum Podcast': 'njmuseum.com',
  'The Hunan Museum Podcast': 'hnmuseum.com',
  'The Hubei Provincial Museum Podcast': 'hbsbwg.com',
  'The Shaanxi History Museum Podcast': 'sxhm.com',
  'The Henan Museum Podcast': 'hnmuseum.org',
  'The Zhejiang Provincial Museum Podcast': 'zjmuseum.org.cn',
  'The Jiangsu Provincial Museum Podcast': 'jspm.cn',
  'The Anhui Provincial Museum Podcast': 'ahm.cn',
  'The Fujian Provincial Museum Podcast': 'fjsmwg.org',
  'The Jiangxi Provincial Museum Podcast': 'jxmuseum.cn',
  'The Shandong Provincial Museum Podcast': 'sdmuseum.org',
  'The Guangdong Provincial Museum Podcast': 'gdmuseum.com',
  'The Guangxi Museum Podcast': 'gxmuseum.cn',
  'The Hainan Provincial Museum Podcast': 'hnmuseum.org',
  'The Sichuan Provincial Museum Podcast': 'scmuseum.cn',
  'The Guizhou Provincial Museum Podcast': 'gzmuseum.com',
  'The Yunnan Provincial Museum Podcast': 'ynmuseum.org',
  'The Tibet Museum Podcast': 'tibetmuseum.cn',
  'The Gansu Provincial Museum Podcast': 'gsmuseum.org',
  'The Qinghai Provincial Museum Podcast': 'qhmuseum.org',
  'The Ningxia Museum Podcast': 'nxmuseum.org',
  'The Xinjiang Museum Podcast': 'xjmuseum.org.cn',
  'The Inner Mongolia Museum Podcast': 'nmgmuseum.org',
  'The Heilongjiang Provincial Museum Podcast': 'hljmuseum.org',
  'The Jilin Provincial Museum Podcast': 'jlmuseum.org',
  'The Liaoning Provincial Museum Podcast': 'lnmuseum.org',
  'The Hebei Provincial Museum Podcast': 'hebeimuseum.org',
  'The Shanxi Provincial Museum Podcast': 'shanximuseum.org',
  'The Shaanxi Provincial Museum Podcast': 'sxmuseum.org',
};

async function updateLogosWithCompanyEnrich() {
  console.log('🚀 Updating logos with CompanyEnrich API...\n');
  
  let updated = 0;
  let skipped = 0;
  let failed = 0;
  
  for (const [toolName, domain] of Object.entries(toolDomains)) {
    try {
      const tool = await prisma.tool.findFirst({
        where: { 
          name: { contains: toolName, mode: 'insensitive' },
          isActive: true 
        },
      });
      
      if (!tool) {
        console.log(`⏭️  Not found: ${toolName}`);
        skipped++;
        continue;
      }
      
      // Skip if already has a non-data URL logo
      if (tool.logo && !tool.logo.startsWith('data:')) {
        console.log(`⏭️  Already has logo: ${toolName}`);
        skipped++;
        continue;
      }
      
      // Use CompanyEnrich logo URL
      const logoUrl = `https://api.companyenrich.com/logo/${domain}`;
      
      // Update database
      await prisma.tool.update({
        where: { id: tool.id },
        data: { logo: logoUrl },
      });
      
      console.log(`✅ Updated: ${toolName} -> ${logoUrl}`);
      updated++;
      
    } catch (error) {
      console.error(`❌ Failed: ${toolName}`, error);
      failed++;
    }
  }
  
  console.log('\n========================================');
  console.log('📊 Results');
  console.log('========================================');
  console.log(`Updated: ${updated}`);
  console.log(`Skipped: ${skipped}`);
  console.log(`Failed:  ${failed}`);
  console.log('========================================\n');
  
  await prisma.$disconnect();
}

updateLogosWithCompanyEnrich();
